"""
Task Adapters for converting AppWorld tasks to MMToolSandbox scenarios.

This module provides utilities to:
1. Convert individual AppWorld tasks to MMToolSandbox ScenarioExtension objects
2. Load entire AppWorld datasets as scenario collections
3. Create conversational variants of AppWorld tasks with vague initial requests
4. Define cross-system scenarios that use both AppWorld and MMToolSandbox tools
5. Load cross-environment tasks from JSON files (generated by mm-intelligence)
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import (
    TYPE_CHECKING,
    Any,
    cast,
)

if TYPE_CHECKING:
    pass

# Pattern matching entity reference IDs like "todoist_project_100", "gmail_email_42"
_ENTITY_REF_ID_RE = re.compile(r"^[a-z][a-z0-9_]*_(\d+)$")

# ---------------------------------------------------------------------------
# Per-table ID offsets
# ---------------------------------------------------------------------------
# Computed from AppWorld base DB max IDs.  Each offset is
# ceil((max_id + 1) / 100) * 100 so staged entities start at the next clean
# hundred above existing data, avoiding ID collisions.
#
# Entity reference strings like "gmail_email_100" are resolved to
# offset + 100 for the target table (e.g. gmail.emails offset=5000 → 5100).
_TABLE_ID_OFFSETS: dict[str, int] = {
    "amazon.addresses": 300,
    "amazon.browsing_history_entries": 2800,
    "amazon.cart_entries": 8400,
    "amazon.deliverers": 100,
    "amazon.order_items": 100,
    "amazon.orders": 3200,
    "amazon.payment_cards": 500,
    "amazon.prime_subscriptions": 100,
    "amazon.product_question_answers": 21200,
    "amazon.product_questions": 10800,
    "amazon.product_recommendations": 100,
    "amazon.product_returns": 100,
    "amazon.product_reviews": 16000,
    "amazon.products": 100,
    "amazon.promos": 100,
    "amazon.sellers": 100,
    "amazon.users": 200,
    "amazon.wish_list_entries": 500,
    "file_system.directories": 3500,
    "file_system.files": 25900,
    "file_system.users": 200,
    "gmail.attachments": 100,
    "gmail.drafts": 600,
    "gmail.emails": 5000,
    "gmail.global_email_threads": 100,
    "gmail.user_email_threads": 47900,
    "gmail.users": 200,
    "phone.alarms": 100,
    "phone.contacts": 100,
    "phone.global_text_messages": 100,
    "phone.global_voice_messages": 100,
    "phone.user_text_messages": 100,
    "phone.user_voice_messages": 100,
    "phone.users": 200,
    "simple_note.notes": 3100,
    "simple_note.users": 200,
    "splitwise.expense_comments": 5400,
    "splitwise.expense_shares": 100,
    "splitwise.expenses": 5100,
    "splitwise.group_members": 1000,
    "splitwise.groups": 300,
    "splitwise.notifications": 35600,
    "splitwise.payment_comments": 3000,
    "splitwise.payments": 6100,
    "splitwise.users": 200,
    "spotify.album_likes": 700,
    "spotify.album_reviews": 400,
    "spotify.albums": 100,
    "spotify.artists": 100,
    "spotify.music_players": 200,
    "spotify.payment_cards": 500,
    "spotify.playlist_likes": 600,
    "spotify.playlist_reviews": 300,
    "spotify.playlist_songs": 100,
    "spotify.playlists": 700,
    "spotify.premium_subscriptions": 200,
    "spotify.recommendations": 2700,
    "spotify.song_likes": 2500,
    "spotify.song_reviews": 300,
    "spotify.songs": 100,
    "spotify.user_artist_followings": 700,
    "spotify.user_downloaded_songs": 3900,
    "spotify.user_library_albums": 700,
    "spotify.user_library_songs": 800,
    "spotify.users": 200,
    "todoist.attachments": 100,
    "todoist.labels": 2300,
    "todoist.notifications": 14000,
    "todoist.project_collaborator_links": 500,
    "todoist.project_invites": 200,
    "todoist.projects": 300,
    "todoist.sections": 100,
    "todoist.sub_tasks": 100,
    "todoist.task_comments": 4900,
    "todoist.task_label_links": 100,
    "todoist.tasks": 6400,
    "todoist.users": 200,
    "venmo.bank_transfers": 100,
    "venmo.friendships": 1200,
    "venmo.notifications": 15800,
    "venmo.payment_cards": 500,
    "venmo.payment_requests": 6100,
    "venmo.transaction_comment_likes": 2300,
    "venmo.transaction_comments": 2500,
    "venmo.transaction_likes": 7800,
    "venmo.transactions": 8300,
    "venmo.users": 200,
}

# Fallback for tables not in the map.
_DEFAULT_ID_OFFSET = 47900

# Keep the old constant for backward compatibility.
_ENTITY_ID_OFFSET = _DEFAULT_ID_OFFSET

# ---------------------------------------------------------------------------
# Entity ID prefix → table mapping
# ---------------------------------------------------------------------------
# Maps the underscore prefix of entity reference strings to their AppWorld
# "app.table" key.  Generated from AppWorld model classes using
# ``inflection.underscore(ClassName)`` as the canonical prefix, plus
# aliases observed in scenario generators.
_ENTITY_PREFIX_TO_TABLE: dict[str, str] = {
    # amazon
    "amazon_address": "amazon.addresses",
    "amazon_browsing_history_entry": "amazon.browsing_history_entries",
    "amazon_cart_entry": "amazon.cart_entries",
    "amazon_deliverer": "amazon.deliverers",
    "amazon_order": "amazon.orders",
    "amazon_order_item": "amazon.order_items",
    "amazon_payment_card": "amazon.payment_cards",
    "amazon_prime_subscription": "amazon.prime_subscriptions",
    "amazon_product": "amazon.products",
    "amazon_product_question": "amazon.product_questions",
    "amazon_product_question_answer": "amazon.product_question_answers",
    "amazon_product_recommendation": "amazon.product_recommendations",
    "amazon_product_return": "amazon.product_returns",
    "amazon_product_review": "amazon.product_reviews",
    "amazon_promo": "amazon.promos",
    "amazon_seller": "amazon.sellers",
    "amazon_user": "amazon.users",
    "amazon_wish_list_entry": "amazon.wish_list_entries",
    # file_system
    "file_system_directory": "file_system.directories",
    "file_system_file": "file_system.files",
    "file_system_user": "file_system.users",
    # gmail
    "gmail_attachment": "gmail.attachments",
    "gmail_draft": "gmail.drafts",
    "gmail_email": "gmail.emails",
    "gmail_global_email_thread": "gmail.global_email_threads",
    "gmail_thread": "gmail.global_email_threads",  # alias
    "gmail_user": "gmail.users",
    "gmail_user_email_thread": "gmail.user_email_threads",
    "gmail_user_thread": "gmail.user_email_threads",  # alias
    # phone
    "alarms_alarm": "phone.alarms",  # alias
    "contacts_contact": "phone.contacts",  # alias
    "phone_alarm": "phone.alarms",
    "phone_contact": "phone.contacts",
    "phone_global_text_message": "phone.global_text_messages",
    "phone_global_voice_message": "phone.global_voice_messages",
    "phone_user": "phone.users",
    "phone_user_text_message": "phone.user_text_messages",
    "phone_user_voice_message": "phone.user_voice_messages",
    "messages_text_message": "phone.global_text_messages",  # alias
    "messages_global_text_message": "phone.global_text_messages",  # alias
    "messages_voice_message": "phone.global_voice_messages",  # alias
    "messages_user_text_message": "phone.user_text_messages",  # alias
    # simple_note
    "simple_note_note": "simple_note.notes",
    "simple_note_user": "simple_note.users",
    # splitwise
    "splitwise_expense": "splitwise.expenses",
    "splitwise_expense_comment": "splitwise.expense_comments",
    "splitwise_expense_share": "splitwise.expense_shares",
    "splitwise_group": "splitwise.groups",
    "splitwise_group_member": "splitwise.group_members",
    "splitwise_notification": "splitwise.notifications",
    "splitwise_payment": "splitwise.payments",
    "splitwise_payment_comment": "splitwise.payment_comments",
    "splitwise_user": "splitwise.users",
    # spotify
    "spotify_album": "spotify.albums",
    "spotify_album_like": "spotify.album_likes",
    "spotify_album_review": "spotify.album_reviews",
    "spotify_artist": "spotify.artists",
    "spotify_music_player": "spotify.music_players",
    "spotify_payment_card": "spotify.payment_cards",
    "spotify_playlist": "spotify.playlists",
    "spotify_playlist_like": "spotify.playlist_likes",
    "spotify_playlist_review": "spotify.playlist_reviews",
    "spotify_playlist_song": "spotify.playlist_songs",
    "spotify_premium_subscription": "spotify.premium_subscriptions",
    "spotify_recommendation": "spotify.recommendations",
    "spotify_song": "spotify.songs",
    "spotify_song_like": "spotify.song_likes",
    "spotify_song_review": "spotify.song_reviews",
    "spotify_user": "spotify.users",
    "spotify_user_artist_following": "spotify.user_artist_followings",
    "spotify_user_downloaded_song": "spotify.user_downloaded_songs",
    "spotify_user_library_album": "spotify.user_library_albums",
    "spotify_user_library_song": "spotify.user_library_songs",
    # todoist
    "todoist_attachment": "todoist.attachments",
    "todoist_label": "todoist.labels",
    "todoist_notification": "todoist.notifications",
    "todoist_project": "todoist.projects",
    "todoist_project_collaborator_link": "todoist.project_collaborator_links",
    "todoist_collaborator_link": "todoist.project_collaborator_links",  # alias
    "todoist_project_invite": "todoist.project_invites",
    "todoist_section": "todoist.sections",
    "todoist_sub_task": "todoist.sub_tasks",
    "todoist_task": "todoist.tasks",
    "todoist_task_comment": "todoist.task_comments",
    "todoist_comment": "todoist.task_comments",  # alias
    "todoist_task_label_link": "todoist.task_label_links",
    "todoist_user": "todoist.users",
    # venmo
    "venmo_bank_transfer": "venmo.bank_transfers",
    "venmo_friendship": "venmo.friendships",
    "venmo_notification": "venmo.notifications",
    "venmo_payment_card": "venmo.payment_cards",
    "venmo_payment_request": "venmo.payment_requests",
    "venmo_transaction": "venmo.transactions",
    "venmo_transaction_comment": "venmo.transaction_comments",
    "venmo_transaction_comment_like": "venmo.transaction_comment_likes",
    "venmo_transaction_like": "venmo.transaction_likes",
    "venmo_user": "venmo.users",
}

# Pre-sorted by prefix length (longest first) for unambiguous matching
_SORTED_PREFIXES = sorted(_ENTITY_PREFIX_TO_TABLE, key=len, reverse=True)


def _resolve_entity_ref(entity_ref: str) -> tuple[str, int] | None:
    """Resolve an entity reference string to (table_key, coerced_id).

    E.g. ``"gmail_email_100"`` → ``("gmail.emails", 5100)`` using the
    per-table offset from ``_TABLE_ID_OFFSETS``.

    Returns None if the string doesn't match any known prefix.
    """
    for prefix in _SORTED_PREFIXES:
        if entity_ref.startswith(prefix + "_"):
            suffix = entity_ref[len(prefix) + 1 :]
            try:
                raw_id = int(suffix)
            except ValueError:
                continue
            table_key = _ENTITY_PREFIX_TO_TABLE[prefix]
            # IDs >= 200 are already above the base DB range for small tables
            # and won't collide, so skip the offset.
            if raw_id >= 200:
                return table_key, raw_id
            offset = _TABLE_ID_OFFSETS.get(table_key, _DEFAULT_ID_OFFSET)
            return table_key, raw_id + offset
    return None


def _coerce_entity_id(col: str, val: Any) -> Any:
    """Convert string entity-reference IDs to integers for SQL insertion.

    Scenario JSONs use string IDs like "todoist_project_100" for readability,
    but AppWorld DB schemas declare these columns as INTEGER. This function
    extracts the trailing integer from such strings and adds a per-table
    offset so IDs don't collide with existing base DB data.

    Also handles list columns (e.g. artist_ids, email_ids) by resolving
    each element in the list.
    """
    if val is None:
        return val
    if isinstance(val, list) and (col == "ids" or col.endswith("_ids")):
        return [_coerce_entity_id("id", elem) for elem in val]
    if not isinstance(val, str):
        return val
    if col != "id" and not col.endswith("_id") and not col.endswith("_ids"):
        return val
    resolved = _resolve_entity_ref(val)
    if resolved is not None:
        return resolved[1]
    return val


def _entity_to_sql_upsert(
    table_key: str,
    entity: dict[str, Any],
) -> tuple[str, str, list[Any]]:
    """
    Convert an entity dict to SQL INSERT OR REPLACE statement.

    Args:
        table_key: The "app.table" key (e.g., "spotify.songs")
        entity: Entity dictionary with field values

    Returns:
        Tuple of (app_name, sql_statement, parameters)
    """
    if "." not in table_key:
        raise ValueError(f"Table key must be 'app.table' format, got: {table_key}")

    app_name, sql_table = table_key.split(".", 1)

    columns = list(entity.keys())
    placeholders = ", ".join(["?" for _ in columns])
    column_str = ", ".join(columns)

    sql = f"INSERT OR REPLACE INTO {sql_table} ({column_str}) VALUES ({placeholders})"

    # Handle JSON serialization for list/dict values and ID coercion
    params = []
    for col in columns:
        val = entity[col]
        # Coerce IDs first (handles both scalars and lists like artist_ids)
        val = _coerce_entity_id(col, val)
        if isinstance(val, (list, dict)):
            params.append(json.dumps(val))
        else:
            params.append(val)

    return app_name, sql, params


def convert_appworld_entities_to_sql(
    appworld_entities: dict[str, list[dict[str, Any]]],
) -> list[tuple[str, str, list[Any]]]:
    """
    Convert Appworld entity dicts to SQL modification tuples.

    Args:
        appworld_entities: Dict mapping "app.table" to list of entity dicts
            Example: {"spotify.songs": [{"id": 1, "title": "Song"}]}

    Returns:
        List of (app_name, sql_statement, parameters) tuples ready for
        bridge.apply_database_modifications()
    """
    modifications = []
    for table_key, entities in appworld_entities.items():
        for entity in entities:
            modifications.append(_entity_to_sql_upsert(table_key, entity))
    return modifications


@dataclass
class AppWorldScenarioConfig:
    """
    Configuration for converting an AppWorld task to a scenario.

    Attributes:
        make_conversational: If True, create multi-turn scenario with vague request
        vague_initial_request: Custom vague request (auto-generated if None)
        include_agentsandbox_tools: If True, include MMToolSandbox tools alongside AppWorld tools
        max_turns: Maximum number of conversation turns
        database_modifications: SQL modifications to apply on top of task state
        setup_code: Python code to run in AppWorld before scenario starts
    """

    make_conversational: bool = True
    vague_initial_request: str | None = None
    include_agentsandbox_tools: bool = False
    max_turns: int = 30
    database_modifications: list[tuple[str, str, list[Any]]] | None = None
    setup_code: str | None = None


def appworld_task_to_scenario(
    task_id: str,
    config: AppWorldScenarioConfig | None = None,
) -> dict[str, Any]:
    """
    Convert an AppWorld task to an MMToolSandbox-compatible scenario definition.

    This function creates a scenario dictionary that can be used to run
    the AppWorld task within MMToolSandbox's conversational framework.

    Args:
        task_id: The AppWorld task ID to convert
        config: Optional configuration for the conversion

    Returns:
        Dictionary with scenario definition including:
            - name: Scenario name (appworld_{task_id})
            - messages: Initial conversation messages
            - tool_allow_list: List of allowed tools
            - categories: Scenario categories
            - metadata: Additional metadata including original task_id

    Raises:
        RuntimeError: If AppWorld is not initialized or task not found
    """
    from mmtoolsandbox.appworld.bridge import (
        AppWorldNotInstalledError,
        get_appworld_bridge,
    )
    from mmtoolsandbox.tools.appworld import get_appworld_tools

    config = config or AppWorldScenarioConfig()

    # Initialize AppWorld bridge for this task
    try:
        bridge = get_appworld_bridge()
        bridge.initialize(task_id)
        task = bridge.task
    except AppWorldNotInstalledError:
        raise RuntimeError(
            "AppWorld is not installed. Install it with 'pip install appworld'"
        )
    except Exception as e:
        raise RuntimeError(f"Failed to load AppWorld task {task_id}: {e}")

    # Get task instruction and supervisor info
    instruction = task.instruction
    supervisor = task.supervisor

    # Build messages based on configuration
    if config.make_conversational and config.vague_initial_request:
        # Multi-turn: start with vague request
        messages = [
            {
                "sender": "SYSTEM",
                "recipient": "USER",
                "content": (
                    f"Your actual goal: {instruction}\n"
                    f"Start with a vague request and provide details when asked."
                ),
            },
            {
                "sender": "USER",
                "recipient": "AGENT",
                "content": config.vague_initial_request,
            },
        ]
        categories = ["MULTIPLE_USER_TURN"]
    else:
        # Single-turn: direct instruction
        messages = [
            {
                "sender": "SYSTEM",
                "recipient": "USER",
                "content": instruction,
            },
            {
                "sender": "USER",
                "recipient": "AGENT",
                "content": instruction,
            },
        ]
        categories = ["SINGLE_USER_TURN"]

    # Get tool list
    appworld_tools = list(get_appworld_tools().keys())

    # Add MMToolSandbox tools if configured
    tool_allow_list = appworld_tools.copy()
    if config.include_agentsandbox_tools:
        # Add core MMToolSandbox tools
        agentsandbox_tools = [
            "search_contacts",
            "add_contact",
            "modify_contact",
            "remove_contact",
            "send_message_with_phone_number",
            "search_messages",
            "add_reminder",
            "modify_reminder",
            "remove_reminder",
            "search_reminder",
            "get_cellular_service_status",
            "set_cellular_service_status",
            "get_wifi_status",
            "set_wifi_status",
            "get_current_location",
            "get_current_timestamp",
        ]
        tool_allow_list.extend(agentsandbox_tools)

    # Build scenario definition
    scenario = {
        "name": f"appworld_{task_id}",
        "messages": messages,
        "tool_allow_list": tool_allow_list,
        "categories": categories,
        "max_turns": config.max_turns,
        "database_modifications": config.database_modifications,
        "setup_code": config.setup_code,
        "metadata": {
            "appworld_task_id": task_id,
            "supervisor": {
                "first_name": supervisor.get("first_name", ""),
                "last_name": supervisor.get("last_name", ""),
                "email": supervisor.get("email", ""),
            },
            "original_instruction": instruction,
            "is_conversational": config.make_conversational,
        },
    }

    return scenario


def load_appworld_scenarios(
    dataset: str = "dev",
    config: AppWorldScenarioConfig | None = None,
    limit: int | None = None,
) -> list[dict[str, Any]]:
    """
    Load all AppWorld tasks from a dataset as MMToolSandbox scenarios.

    Args:
        dataset: AppWorld dataset name ("train", "dev", "test_normal", "test_challenge")
        config: Optional configuration for all conversions
        limit: Optional limit on number of scenarios to load

    Returns:
        List of scenario dictionaries

    Raises:
        RuntimeError: If AppWorld is not installed
    """
    from mmtoolsandbox.appworld.bridge import (
        AppWorldNotInstalledError,
        load_task_ids,
    )

    try:
        task_ids = load_task_ids(dataset)
    except AppWorldNotInstalledError:
        raise RuntimeError(
            "AppWorld is not installed. Install it with 'pip install appworld'"
        )

    if limit is not None:
        task_ids = task_ids[:limit]

    scenarios = []
    for task_id in task_ids:
        try:
            scenario = appworld_task_to_scenario(task_id, config)
            scenarios.append(scenario)
        except Exception as e:
            # Log error but continue with other tasks
            print(f"Warning: Failed to convert task {task_id}: {e}")
            continue

    return scenarios


def create_cross_system_scenario(
    name: str,
    instruction: str,
    vague_request: str | None = None,
    appworld_tools: list[str] | None = None,
    agentsandbox_tools: list[str] | None = None,
    starting_state: dict[str, Any] | None = None,
    database_modifications: list[tuple[str, str, list[Any]]] | None = None,
    appworld_entities: dict[str, list[dict[str, Any]]] | None = None,
    setup_code: str | None = None,
    base_task_id: str | None = None,
    agentsandbox_base: str = "base",
    max_turns: int = 30,
    categories: list[str] | None = None,
) -> dict[str, Any]:
    """
    Create a cross-system scenario that uses tools from both AppWorld and MMToolSandbox.

    This enables scenarios like:
    - "Send a song from Spotify to a contact via SMS"
    - "Create a reminder when an Amazon order arrives"
    - "Pay a friend on Venmo and text them confirmation"

    Args:
        name: Unique name for the scenario
        instruction: The full task instruction
        vague_request: Optional vague initial request for multi-turn
        appworld_tools: List of AppWorld tool names to include
        agentsandbox_tools: List of MMToolSandbox tool names to include
        starting_state: MMToolSandbox entity modifications (dict of namespace -> entity list)
        database_modifications: SQL modifications for AppWorld (list of (app, sql, params))
        appworld_entities: Appworld entity dicts to convert to SQL (dict of "app.table" -> entity list)
        setup_code: Python code to run in AppWorld before scenario starts
        base_task_id: AppWorld task ID to use as base (determines Appworld database state)
        agentsandbox_base: MMToolSandbox base variant ("base", "base_cellular_off", etc.)
        max_turns: Maximum conversation turns
        categories: Additional categories for the scenario

    Returns:
        Scenario dictionary with cross-system configuration

    Example:
        scenario = create_cross_system_scenario(
            name="share_spotify_song_via_sms",
            instruction="Share the last song I played on Spotify with John via text message",
            appworld_tools=["spotify_get_recently_played"],
            agentsandbox_tools=["search_contacts", "send_message_with_phone_number"],
            starting_state={
                "contact": [{"person_id": "p1", "name": "John", "phone_number": "+1234567890"}],
            },
            appworld_entities={
                "spotify.songs": [{"id": 9999, "title": "My Song", "artist_id": 1}],
            },
            base_task_id="1",
            agentsandbox_base="base",
        )
    """
    # Build messages
    if vague_request:
        messages = [
            {
                "sender": "SYSTEM",
                "recipient": "USER",
                "content": (
                    f"Your actual goal: {instruction}\n"
                    f"Start with a vague request and provide details when asked."
                ),
            },
            {
                "sender": "USER",
                "recipient": "AGENT",
                "content": vague_request,
            },
        ]
        base_categories = ["MULTIPLE_USER_TURN", "CROSS_SYSTEM"]
    else:
        messages = [
            {
                "sender": "SYSTEM",
                "recipient": "USER",
                "content": instruction,
            },
            {
                "sender": "USER",
                "recipient": "AGENT",
                "content": instruction,
            },
        ]
        base_categories = ["SINGLE_USER_TURN", "CROSS_SYSTEM"]

    # Merge categories
    final_categories = base_categories + (categories or [])

    # Combine tool lists
    tool_allow_list = []
    if appworld_tools:
        tool_allow_list.extend(appworld_tools)
    if agentsandbox_tools:
        tool_allow_list.extend(agentsandbox_tools)

    # Convert appworld_entities to SQL modifications
    final_db_modifications = (
        list(database_modifications) if database_modifications else []
    )
    if appworld_entities:
        final_db_modifications.extend(
            convert_appworld_entities_to_sql(appworld_entities)
        )

    # Build scenario
    scenario = {
        "name": name,
        "messages": messages,
        "tool_allow_list": tool_allow_list if tool_allow_list else None,
        "categories": final_categories,
        "starting_state": starting_state,
        "database_modifications": final_db_modifications
        if final_db_modifications
        else None,
        "setup_code": setup_code,
        "base_task_id": base_task_id,
        "agentsandbox_base": agentsandbox_base,
        "max_turns": max_turns,
        "metadata": {
            "is_cross_system": True,
            "appworld_tools": appworld_tools or [],
            "agentsandbox_tools": agentsandbox_tools or [],
        },
    }

    return scenario


# Pre-defined cross-system scenario templates
CROSS_SYSTEM_TEMPLATES = {
    "share_song_via_sms": {
        "name": "share_spotify_song_via_sms",
        "instruction": "Share the last song I played on Spotify with {contact_name} via text message",
        "vague_request": "I want to share a song with my friend",
        "appworld_tools": ["spotify_login", "spotify_get_recently_played"],
        "agentsandbox_tools": [
            "search_contacts",
            "send_message_with_phone_number",
            "get_cellular_service_status",
            "set_cellular_service_status",
        ],
    },
    "payment_confirmation_sms": {
        "name": "venmo_payment_with_sms_confirmation",
        "instruction": "Pay {contact_name} ${amount} on Venmo and send them a confirmation text",
        "vague_request": "I need to pay my friend and let them know",
        "appworld_tools": ["venmo_login", "venmo_send_payment"],
        "agentsandbox_tools": [
            "search_contacts",
            "send_message_with_phone_number",
            "get_cellular_service_status",
            "set_cellular_service_status",
        ],
    },
    "order_reminder": {
        "name": "amazon_order_reminder",
        "instruction": "Check my recent Amazon orders and create a reminder for when the package arrives",
        "vague_request": "I ordered something, remind me when it comes",
        "appworld_tools": ["amazon_login", "amazon_get_orders"],
        "agentsandbox_tools": [
            "add_reminder",
            "get_current_timestamp",
            "shift_timestamp",
        ],
    },
}


def create_from_template(
    template_name: str,
    **kwargs: Any,
) -> dict[str, Any]:
    """
    Create a cross-system scenario from a pre-defined template.

    Args:
        template_name: Name of the template (e.g., "share_song_via_sms")
        **kwargs: Template variables to substitute (e.g., contact_name="John")

    Returns:
        Scenario dictionary with substituted values

    Raises:
        KeyError: If template_name is not found
    """
    if template_name not in CROSS_SYSTEM_TEMPLATES:
        available = ", ".join(CROSS_SYSTEM_TEMPLATES.keys())
        raise KeyError(f"Template '{template_name}' not found. Available: {available}")

    template = CROSS_SYSTEM_TEMPLATES[template_name].copy()

    # Substitute variables in instruction and vague_request
    if kwargs:
        instruction = template.get("instruction")
        if isinstance(instruction, str):
            template["instruction"] = instruction.format(**kwargs)
        vague_request = template.get("vague_request")
        if isinstance(vague_request, str):
            template["vague_request"] = vague_request.format(**kwargs)

    return create_cross_system_scenario(**template)  # type: ignore[arg-type]


def load_cross_environment_task(
    path: str | Path,
) -> dict[str, Any]:
    """
    Load a cross-environment task from a JSON file and convert to scenario dict.

    Expected JSON format:
    {
        "task_id": "cross_spotify_sms_001",
        "instruction": "Share my recently played Spotify song with John via text",

        // Base states
        "agentsandbox_base": "base",           // "base", "base_cellular_off", etc.
        "appworld_base_task": "1",             // Appworld task ID for base DB state

        // Entity modifications (on top of base states)
        "agentsandbox_entities": {
            "contact": [{"person_id": "p1", "name": "John", ...}],
            "calendar_events": [...]
        },
        "appworld_entities": {
            "spotify.songs": [{"id": 9999, "title": "My Song", ...}],
            "amazon.products": [...]
        },

        // Tool configuration
        "tool_allow_list": ["spotify_get_recently_played", "search_contacts", ...],

        // Optional
        "vague_initial_request": "I want to share a song",
        "categories": ["CROSS_ENVIRONMENT", "SPOTIFY"],
        "max_turns": 30
    }

    Args:
        path: Path to the JSON task file

    Returns:
        Scenario dictionary ready for use with AppWorldScenarioRunner
    """
    path = Path(path)
    with open(path, "r") as f:
        data = json.load(f)

    task_id = data.get("task_id", path.stem)
    instruction = data["instruction"]

    # Parse tool lists
    tool_allow_list = data.get("tool_allow_list", [])

    # Separate tools by environment (Appworld tools have app prefix)
    appworld_prefixes = {
        "spotify",
        "amazon",
        "gmail",
        "venmo",
        "todoist",
        "splitwise",
        "phone",
        "file_system",
        "simple_note",
        "admin",
        "supervisor",
    }

    appworld_tools = []
    agentsandbox_tools = []
    for tool in tool_allow_list:
        is_appworld = any(
            tool.startswith(f"{prefix}_") or tool.startswith(f"{prefix}__")
            for prefix in appworld_prefixes
        )
        if is_appworld:
            appworld_tools.append(tool)
        else:
            agentsandbox_tools.append(tool)

    return create_cross_system_scenario(
        name=task_id,
        instruction=instruction,
        vague_request=data.get("vague_initial_request"),
        appworld_tools=appworld_tools if appworld_tools else None,
        agentsandbox_tools=agentsandbox_tools if agentsandbox_tools else None,
        starting_state=data.get("agentsandbox_entities"),
        appworld_entities=data.get("appworld_entities"),
        base_task_id=data.get("appworld_base_task"),
        agentsandbox_base=data.get("agentsandbox_base", "base"),
        max_turns=data.get("max_turns", 30),
        categories=data.get("categories"),
    )


def load_cross_environment_tasks(
    directory: str | Path,
    pattern: str = "*.json",
) -> list[dict[str, Any]]:
    """
    Load multiple cross-environment tasks from a directory.

    Args:
        directory: Directory containing task JSON files
        pattern: Glob pattern to match files (default: "*.json")

    Returns:
        List of scenario dictionaries
    """
    directory = Path(directory)
    scenarios = []

    for json_file in sorted(directory.glob(pattern)):
        try:
            scenario = load_cross_environment_task(json_file)
            scenarios.append(scenario)
        except Exception as e:
            print(f"Warning: Failed to load {json_file}: {e}")
            continue

    return scenarios


def load_appworld_task(
    path: str | Path,
) -> dict[str, Any]:
    """
    Load a converted visual-tool-calling task from a JSON file.

    These files are produced by convert_visual_scenarios.py and contain
    pre-separated appworld_entities, agentsandbox_entities, milestones, etc.

    Args:
        path: Path to the converted scenario JSON file.

    Returns:
        Scenario dictionary ready for use with run_appworld_task().
    """
    path = Path(path)
    with open(path, "r") as f:
        return cast(dict[str, Any], json.load(f))


def load_appworld_tasks(
    directory: str | Path,
    pattern: str = "scenario_*.json",
) -> list[dict[str, Any]]:
    """
    Load multiple converted visual-tool-calling tasks from a directory.

    Args:
        directory: Directory containing converted scenario JSON files.
        pattern: Glob pattern to match files (default: "scenario_*.json").

    Returns:
        List of scenario dictionaries.
    """
    directory = Path(directory)
    scenarios = []

    for json_file in sorted(directory.glob(pattern)):
        try:
            scenario = load_appworld_task(json_file)
            scenarios.append(scenario)
        except Exception as e:
            print(f"Warning: Failed to load {json_file}: {e}")
            continue

    return scenarios
