# Copyright © 2026 Apple Inc.

"""Thread-local execution context for MMToolSandbox simulations.

Provides ``ExecutionContext``, the singleton that holds all world state for
a running scenario: polars databases, the interactive REPL console, the
tool registry (with LRU cache and role-based permissions), and the safety
guard.  Access the current context via ``get_current_context()``; manage
its lifecycle with the ``new_context()`` context manager.

Note: The current implementation uses a thread-local global rather than
proper dependency injection.  This is not thread-safe across shared
mutable state — each thread/process must manage its own context.
"""

from __future__ import annotations

import bisect
import code
import contextlib
import copy
import functools
import json
import pathlib
import threading
from enum import auto
from logging import getLogger
from typing import (
    Any,
    Callable,
    Iterator,
    cast,
)

import dill  # type: ignore[import-untyped]
import polars as pl
from polars.exceptions import NoDataError
from polars.type_aliases import IntoExprColumn
from strenum import StrEnum

# Re-exported so downstream modules can import from this module.
from mmtoolsandbox.common.databases import DatabaseNamespace as DatabaseNamespace
from mmtoolsandbox.common.i18n import Locale
from mmtoolsandbox.common.image_id import ImageId
from mmtoolsandbox.common.introspection_databases import (
    IntrospectionDatabaseManager,
    IntrospectionDatabaseNamespace,
)
from mmtoolsandbox.common.safety_guard import SafetyGuard, SafetyGuardConfig
from mmtoolsandbox.toolbox.tool_state_registry import (
    ToolStateRegistry,
)
from mmtoolsandbox.toolbox.toolbox import Toolbox, create_empty_toolbox


class RoleType(StrEnum):
    """Types of roles available in the sandbox"""

    SYSTEM = auto()
    USER = auto()
    AGENT = auto()
    EXECUTION_ENVIRONMENT = auto()


class CalendarRecurrenceFrequencyType(StrEnum):
    """Types of recurrence frequencies for Calendar"""

    YEARLY = auto()
    MONTHLY = auto()
    WEEKLY = auto()
    DAILY = auto()


class ScenarioCategories(StrEnum):
    """Categorical enum describing scenarios. Each scenario can belong to multiple categories"""

    # Scenario that requires a single tool call to complete
    SINGLE_TOOL_CALL = auto()
    # Scenario that requires a multiple tool call to complete
    MULTIPLE_TOOL_CALL = auto()
    # Scenario that requires a single user turn to complete. Note that this doesn't mean
    # there has to be only 1 user turn in the trajectory. If the agent attempted to look for help
    # from the user, there could be multiple user turns in the rollout
    SINGLE_USER_TURN = auto()
    # Scenario that requires a multiple user turn to complete.
    MULTIPLE_USER_TURN = auto()
    # Scenario that involves tools that depends on certain expected world state, and raises error if the expectation
    # is not met
    STATE_DEPENDENCY = auto()
    # Scenario that requires surface form text to be transformed into canonical form
    CANONICALIZATION = auto()
    # Scenario that requires co-reference resolution
    COREFERENCE = auto()
    # Scenario that requires disambiguation between multiple entities / tool choices
    DISAMBIGUATION = auto()
    # Scenario that cannot be completed with the provided tools / user prompts
    INSUFFICIENT_INFORMATION = auto()
    # Tool augmentations
    # All tools provided are necessary to complete the scenario
    NO_DISTRACTION_TOOLS = auto()
    # 3 distraction tools provided in addition to necessary ones
    THREE_DISTRACTION_TOOLS = auto()
    # 10 distraction tools provided in addition to necessary ones
    TEN_DISTRACTION_TOOLS = auto()
    # All tools in the sandbox provided
    ALL_TOOLS_AVAILABLE = auto()
    # Image provided in user turn
    VISION_USER_IMAGE = auto()
    # Image necessary for tasks completion is returned by tool
    VISION_TOOL_RESULT_IMAGE = auto()
    # Multiple images will need to be processed by model
    VISION_MULTIPLE_IMAGES = auto()
    # Human annotated reference scenarios
    VISION_REFERENCE = auto()
    # Vision scenarios that require search and image manipulation (VQA)
    VISION_VQA = auto()
    # Vision scenarios generated by the synthetic scenario generation pipeline
    VISION_SYNTHETIC = auto()


LOGGER = getLogger(__name__)

# Maximum number of tools allowed in the active tool cache (LRU)
MAX_ACTIVE_TOOLS = 100


class ExecutionContext:
    """Execution Context for sandbox simulation.

    Each ExecutionContext object is a full encapsulation of the sandbox world state, which

    1. Contains database for multiple tools which enables stateful execution
    without listing world state as function arguments.
    2. Contains database for messages, capturing conversation between different roles
    3. Contains an InteractiveConsole object used to execute code snippets coming from the agent

    All database contains a full history of how the database changed across time. Time is indexed by a column
    "sandbox_message_index", which connects other databases with Agent database. When a state database change happened,
    a snapshot of the most recent database state is created. The new snapshot is linked to the message causing the
    change, so that we can recover at any given point what the world state is without unnecessary duplication.

    All database also contains a null row as "headguard", making sure we can represent an empty snapshot

    One should instantiate this class as a global variable
    for all tools to access without taking ExecutionContext as function argument

    Attributes:
        interactive_console: Python ``code.InteractiveConsole`` used to execute
            agent-generated code snippets.
        tool_allow_list: When not None, only tools with these names are accessible
            to the agent.  None means all tools are allowed.
        role_tool_allow_list: Per-role tool allow lists keyed by ``RoleType``.
        tool_deny_list: When not None, tools in this list are blocked.
        trace_tool: When True, tool inputs and outputs are saved alongside
            messages in the SANDBOX database.
        pure_code_exec: When True, enables pure code execution mode where
            ``api_docs_search_api_docs`` returns detailed schemas.
        trace_nested_tool: When True, nested tool calls are collected in an
            n-ary tree structure.
        external_tool_schemas: Optional list of external OpenAI tool schemas for
            hybrid annotation workflows.
        active_tool_cache: LRU-ordered list of active tool names for code
            execution mode, with most recently used at the end.
        pinned_tools: Set of tool names that are never evicted from the LRU
            cache.
        toolbox: The ``Toolbox`` instance containing all registered tools.
        name_to_tool: Mapping from tool name to the callable tool function.
        safety_guard: Optional ``SafetyGuard`` for 3-layer code execution safety.
    """

    # Database schema. Declared as class attributes so that it could be available prior to init
    # As you add more databases / columns, remember to also add their default similarity measure to
    # mmtoolsandbox.common.evaluation._default_dbs_column_similarities
    dbs_schemas: dict[DatabaseNamespace, dict[str, Any]] = {
        # Reserved database for conversation state management
        DatabaseNamespace.SANDBOX: {
            "sandbox_message_index": pl.Int32,
            "sender": pl.Enum([x for x in RoleType]),
            "recipient": pl.Enum([x for x in RoleType]),
            "content": pl.String,
            "openai_tool_call_id": pl.String,
            "openai_function_name": pl.String,
            "conversation_active": pl.Boolean,
            "tool_call_exception": pl.String,
            "tool_trace": pl.List(pl.String),
            "visible_to": pl.List(pl.Enum([x for x in RoleType])),
            "finish_reason": pl.String,
            "logprobs": pl.List(pl.Float64),
            "generation": pl.String,
            "token_ids": pl.List(pl.Int32),
            "claude_text_response": pl.String,
            "claude_extended_thinking": pl.String,
            "claude_extended_thinking_signature": pl.String,
            "tool_call_text_response": pl.String,
            "image_ids": pl.List(pl.Int32),
            "reasoning_trace": pl.String,
            "openai_reasoning_content": pl.String,
            "openai_reasoning_items": pl.String,
        },
        # Database for image storage and management
        DatabaseNamespace.IMAGE: {
            "sandbox_message_index": pl.Int32,
            "image_id": pl.Int32,
            "image_content": pl.String,  # Base64 encoded image data
        },
        # Databases introduced in ToolSandbox publication
        DatabaseNamespace.SETTING: {
            "sandbox_message_index": pl.Int32,
            "device_id": pl.String,
            "cellular": pl.Boolean,
            "wifi": pl.Boolean,
            "location_service": pl.Boolean,
            "low_battery_mode": pl.Boolean,
            "locale": pl.Enum([x.name for x in Locale]),
            "utc_offset_seconds": pl.Int32,  # UTC offset of current timezone in seconds.
            "latitude": pl.Float64,
            "longitude": pl.Float64,
            "place_id": pl.String,
            "formatted_address": pl.String,
        },
        DatabaseNamespace.CONTACT: {
            "sandbox_message_index": pl.Int32,
            "person_id": pl.String,
            "name": pl.String,
            "phone_number": pl.String,
            "relationship": pl.String,
            "is_self": pl.Boolean,
        },
        DatabaseNamespace.MESSAGING: {
            "sandbox_message_index": pl.Int32,
            "message_id": pl.String,
            "sender_person_id": pl.String,
            "sender_phone_number": pl.String,
            "recipient_person_id": pl.String,
            "recipient_phone_number": pl.String,
            "content": pl.String,
            "creation_timestamp": pl.Float64,
            "image_ids": pl.List(pl.Int32),
        },
        DatabaseNamespace.REMINDER: {
            "sandbox_message_index": pl.Int32,
            "reminder_id": pl.String,
            "content": pl.String,
            "creation_datetime": pl.String,
            "reminder_datetime": pl.String,
            "latitude": pl.Float64,
            "longitude": pl.Float64,
        },
        DatabaseNamespace.NOTES: {
            "sandbox_message_index": pl.Int32,
            "note_id": pl.String,
            "content": pl.String,
            "modification_timestamp": pl.Float64,
            "image_ids": pl.List(pl.Int32),
        },
        # Dataset representing Calendars. Not to be confused with Calendar Events, which Calendars contain.
        # Loosely based on the schema found in the macOS Calendar App.
        DatabaseNamespace.CALENDARS: {
            "sandbox_message_index": pl.Int32,
            "calendar_id": pl.String,  # UUID referring to the calendar entity.
            "title": pl.String,  # Title string describing the calendar. E.g. birthday.
        },
        # Dataset representing Calendar Events, each belonging to a calendar.
        # Loosely based on:
        # - The schema found in the macOS Calendar App
        # - iCalendar specification RFC 5545
        #   - https://datatracker.ietf.org/doc/html/rfc5545.html
        # Also see: https://devguide.calconnect.org/Table-of-Contents
        DatabaseNamespace.CALENDAR_EVENTS: {
            "sandbox_message_index": pl.Int32,
            "calendar_event_id": pl.String,  # UUID referring to the calendar event entity
            "calendar_id": pl.String,  # Calendar this event belongs to
            "title": pl.String,  # Represents a title or summary for the event
            "description": pl.String,  # Detailed description of the event
            "start_datetime": pl.String,  # At init time, this field could be a json SerializableRelativeDelta.
            # At scenario.play this becomes ISO 8601 representing event start time, inclusive. Floating is not supported
            "end_datetime": pl.String,  # At init time, this field could be a json SerializableRelativeDelta.
            # At scenario.play this becomes ISO 8601 representing event start time, inclusive. Floating is not supported
            "is_all_day": pl.Boolean,  # Boolean value indicating if this is an all day event.
            # Recurrence rule below
            #   We only implement a subset of recurrence rules defined in
            #   https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.10
            #   This is the subset possible to achieve as of iOS 18.0
            "recurrence_frequency": pl.Enum(
                [x for x in CalendarRecurrenceFrequencyType]
            ),  # Unit of recurrence frequency
            "recurrence_interval": pl.Int32,  # Combined with unit, forms a recurrence rule.
            # E.g. interval of 2 and frequency of WEEKLY means biweekly
            "recurrence_until_datetime": pl.String,  # At init time, this field could be a dilled relativedelta.
            # At scenario.play this becomes ISO 8601 representing end of recurrence.
            "recurrence_parent_id": pl.String,  # Used by overriden recurrence event to point to its parent recurrence.
            "recurrence_exclude_datetime": pl.List(
                pl.String
            ),  # At init time, this field could be a json SerializableRelativeDelta
            # list. At scenario.play this becomes ISO 8601 datetime to be excluded from recurrence.
            # Useful for when an instance of recurring event was modified, and needed to be excluded.
            # Location info below
            "latitude": pl.Float64,  # Canonical Location Info
            "longitude": pl.Float64,  # Canonical Location Info
            "place_id": pl.String,  # Canonical Location Info
            "formatted_address": pl.String,  # Canonical Location Info
            # Attendee info below. It'd be much better if it can be a list of a struct.
            "attendee_names": pl.List(pl.String),
            "attendee_emails": pl.List(pl.String),  # 1 to 1 maps to names.
            # Attendee canonical id is not yet supported; requires Contact rework.
        },
    }
    # Staging Database for recurring calendar events.
    #
    # This database is created to handle the tricky issue of recurring events without a recurrence_until_datetime:
    #   1. Individual events in a recurrence series can sometimes be modified / deleted, which requires an uuid to
    #   uniquely identify it.
    #   2. However, recurrence events are stored with the first event and recurrence rules. A uuid doesn't exist
    #   for individual instances. It is also not possible to unroll all recurrence instances into the database,
    #   considering recurring events without a recurrence_until_datetime have infinite instances.
    #
    # Because of this, we introduce the idea of a staging area, under the following assumptions:
    #   1. Editing instances of a recurring event can only happen after search_calendar_events was called, with
    #   a specific time range.
    #   2. Upon calling search_calendar_events, we realize recurrence instances that fits within the time range,
    #   ready to be edited / removed.
    #   3. If an instance was edited, we update the instance and remove it from CALENDAR_EVENTS_RECURRENCE_STAGING,
    #   commit it to CALENDAR_EVENTS, and exclude the original datetime of the instance in recurrence parent.
    #   4. If an instance was removed, we do all the above except committing to CALENDAR_EVENTS.
    #   5. If a recurrence parent was modified (e.g. the whole recurrence was updated to a different frequency),
    #   all its child staged instances should be purged in CALENDAR_EVENTS_RECURRENCE_STAGING.
    # We choose to do this in CALENDAR_EVENTS_RECURRENCE_STAGING db instead of CALENDAR_EVENTS so as not to introduce
    # unnecessary modification to the db, and doesn't interfere with evaluation. (i.e. we don't want search to become
    # a stateful action in the view of CALENDAR_EVENTS)

    dbs_schemas[DatabaseNamespace.CALENDAR_EVENTS_RECURRENCE_STAGING] = dbs_schemas[
        DatabaseNamespace.CALENDAR_EVENTS
    ]

    def __init__(
        self,
        toolbox: Toolbox | None = None,
        tool_allow_list: list[str] | None = None,
        tool_deny_list: list[str] | None = None,
        delay_initialization: bool = False,
        support_images: bool = False,
        safety_guard_config: SafetyGuardConfig | None = SafetyGuardConfig(),
    ):
        """Init function for ExecutionContext

        Args:
            toolbox:                            The toolbox to use. The main motivation for
                                                making it optional is to allow default
                                                construction of the `ExecutionContext`.
            tool_allow_list:                    Override the default init values for self.tool_allow_list.
            tool_deny_list:                     Override the default init values for self.tool_deny_list.
            delay_initialization:               If false, call `execute_delayed_initialization`.
                                                Otherwise leave it up to the user to call it at
                                                a later time. The motivation is to skip "heavy
                                                work" while loading a dataset and only perform
                                                the work before running the scenarios.
            support_images:                     Whether to initialize the execution context for image handling and
                                                storage. If set to false, adding images will raise an exception.
            safety_guard_config:                Configuration for the safety guard. Defaults to
                                                ``SafetyGuardConfig()`` (enabled). Pass ``None``
                                                to disable the safety guard entirely.
        """
        # If a toolbox is given only set up the databases that the tools need access to.
        # This would be cleaner if the `ExecutionContext` was directly created with the
        # desired toolbox instead of setting it later, which goes back to removing the
        # `ExecutionContext` as a global variable and instead creating it when running a
        # scenario (not sure if that is possible since some of the scenario setup might
        # need the `ExecutionContext` already).
        database_namespaces = (
            set(self.dbs_schemas.keys())
            if toolbox is None
            else toolbox.extract_database_namespaces()
        )
        # Always ensure SANDBOX database is included as it's needed for conversation management
        database_namespaces.add(DatabaseNamespace.SANDBOX)
        # Include image database for image management if required
        if support_images:
            database_namespaces.add(DatabaseNamespace.IMAGE)
        # Each database starts with a full null headguard except on
        # "sandbox_message_index" column, which is set to 0.
        self._dbs = {
            namespace: self._make_null_df(namespace)
            for namespace in self.dbs_schemas
            if namespace in database_namespaces
        }

        self._introspection_db_manager = IntrospectionDatabaseManager()

        self.interactive_console = code.InteractiveConsole()
        # If is None, allow all tools, otherwise only allow tools with these names to be accessed by the Agent
        self.tool_allow_list: list[str] | None = tool_allow_list
        # Role-specific tool allow lists. If a role is in this dict, its tools are further restricted by this list.
        self.role_tool_allow_list: dict[RoleType, list[str]] = {}
        # If is None, deny no tools, otherwise any tool name present in this list cannot be accessed by the Agent
        self.tool_deny_list: list[str] | None = tool_deny_list
        # Config for "tracing" tools. If True, input and output to tools will be saved in Sandbox database alongside
        # corresponding message
        self.trace_tool: bool = False
        # Config for pure code execution mode. If True, tools like
        # api_docs_search_api_docs return detailed schemas instead of
        # registration-only messages.
        self.pure_code_exec: bool = False
        # Config for tracing tool inside tools. If True, tool calls inside a tool call are collected
        # in an n-nary tree structure
        self.trace_nested_tool: bool = False
        # Store externally enabled tool schemas, expressed as openai api tool schemas already
        # When it is not None, allow external tools to be added to tool allow list and available tools
        # Particularly useful for hybrid annotation workflow where tool execution is handled on vendor side.
        # When an external tool is predicted, the message is committed, and execution is terminated,
        # allowing vendor to execute tool call and populate results
        self.external_tool_schemas: list[dict[str, Any]] | None = None

        # LRU Cache for active tools in Code Execution Mode
        # Stores tool names in order of usage (most recent at the end)
        self.active_tool_cache: list[str] = []

        # Tools that should never be evicted from the LRU cache.
        # Used for scenario-defined tools that must remain
        # available throughout the conversation.
        self.pinned_tools: set[str] = set()

        # Toolbox-related items live here for now; moving them into Scenario
        # would require decoupling tool registration from the global context.
        self.toolbox = create_empty_toolbox() if toolbox is None else toolbox
        self.name_to_tool = {tool.__name__: tool for tool in self.toolbox.tools}

        # Initialize the tool state registry as `None` so that we can easily detect the
        # case where the delayed initialization was not executed.
        self._tool_state_registry: ToolStateRegistry | None = None
        if not delay_initialization:
            self.execute_delayed_initialization()

        # Safety guard for agent-generated code
        self.safety_guard: SafetyGuard | None = (
            SafetyGuard(safety_guard_config)
            if safety_guard_config is not None
            else None
        )

    def set_safety_guard_output_directory(self, output_directory: pathlib.Path) -> None:
        """Configure the safety guard to allow writes to *output_directory*.

        Should be called after the execution context is set up and before
        agent code runs.  Safe to call even if the safety guard is disabled.
        """
        if self.safety_guard is not None:
            resolved = str(output_directory.resolve())
            self.safety_guard.config.allowed_write_paths = [resolved]

    def _make_null_df(self, namespace: DatabaseNamespace, idx: int = 0) -> pl.DataFrame:
        """Create a null DataFrame.

        This is useful as a headguard, etc.

        Args:
            namespace:  DatabaseNamespace we want to create a null DataFrame for.
            idx:        Index to use for 'sandbox_message_index'. Defaults to 0.

        Returns:
            Polars DataFrame containing a single null row.
        """
        return pl.DataFrame(
            {
                k: None if k != "sandbox_message_index" else idx
                for k in self.dbs_schemas[namespace]
            },
            schema=self.dbs_schemas[namespace],
        )

    def execute_delayed_initialization(
        self,
        tool_allow_list: list[str] | None = None,
        tool_deny_list: list[str] | None = None,
    ) -> None:
        """Perform heavy initialization deferred from ``__init__``.

        Creates the ``ToolStateRegistry`` (which computes and stores tool
        embeddings).  This is separated from ``__init__`` so that loading a
        dataset of many ``Scenario`` objects does not require GBs of RAM for
        embedding models.  Must be called exactly once before the scenario is
        played.

        Args:
            tool_allow_list: Optional tool names to pass through to
                ``Toolbox.create_tool_state_registry``.
            tool_deny_list: Optional tool names to pass through to
                ``Toolbox.create_tool_state_registry``.

        Raises:
            RuntimeError: If called more than once on the same context.
        """
        # This delayed initialization is a workaround. The problem it solves is:
        # - The tool state registry for the `SWAI_AGENTIC` toolbox computes and stores
        #   embeddings of all tools. So under the hood we are also storing an embedding
        #   model since when running tool retrieval we need to compute the embeddings of
        #   the query. This embedding model can easily occupy a few hundred MBs of RAM.
        # - A dataset consists of `Scenario`s and each of them consists an
        #   `ExecutionContext`.
        # So if we were to add the tool state registry when instantiating the
        # `ExecutionContext` then just loading a dataset would require GBs of RAM
        # scaling with the number of scenarios. As a workaround we delay initialization
        # of the RAM intensive objects until we actually run a scenario. This way,
        # dataset loading does not require egregious amounts of a RAM. A long-term
        # solution would be to change the dataset/scenario definitions to be lightweight
        # and only turn them into `Scenario`s when actually running them.
        if self._tool_state_registry is not None:
            raise RuntimeError(
                "Delayed initialization of the `ExecutionContext` has already been "
                "performed."
            )
        self._tool_state_registry = self.toolbox.create_tool_state_registry(
            tool_allow_list=tool_allow_list, tool_deny_list=tool_deny_list
        )

    def get_tool_state_registry(self) -> ToolStateRegistry:
        """Return the ``ToolStateRegistry`` for this context.

        Returns:
            The initialized tool state registry.

        Raises:
            RuntimeError: If ``execute_delayed_initialization`` has not been
                called yet.
        """
        if self._tool_state_registry is None:
            raise RuntimeError(
                "The tool state registry must be initialized by calling "
                "`execute_delayed_initialization` before trying to access it."
            )

        return self._tool_state_registry

    def get_active_database_namespaces(self) -> set[DatabaseNamespace]:
        """Return the set of database namespaces active in this context.

        Returns:
            A set of ``DatabaseNamespace`` values that have been initialized.
        """
        return set(self._dbs.keys())

    def get_introspection_database_manager(self) -> IntrospectionDatabaseManager:
        """Return the introspection database manager for this context.

        Returns:
            The ``IntrospectionDatabaseManager`` instance.
        """
        return self._introspection_db_manager

    def get_toolbox(self) -> Toolbox:
        """Return the ``Toolbox`` associated with this context.

        Returns:
            The ``Toolbox`` instance containing all registered tools.
        """
        return self.toolbox

    def add_image(self, image_base64: str) -> ImageId:
        """Add an image to the IMAGE database and return its assigned ID.

        The image ID is automatically generated as a sequential ID.

        Args:
            image_base64: Base64 encoded image data

        Returns:
            ImageId: The assigned image identifier
        """
        # Check if IMAGE database is available
        if DatabaseNamespace.IMAGE not in self._dbs:
            raise RuntimeError(
                "IMAGE database is not available in this ExecutionContext. "
            )

        # Count existing images and generate the next image id.
        image_db = self.get_database(DatabaseNamespace.IMAGE)
        image_count = len(image_db)
        image_id = ImageId(image_count)

        # Add the image to the database
        self.add_to_database(
            namespace=DatabaseNamespace.IMAGE,
            rows=[{"image_id": image_id, "image_content": image_base64}],
        )

        return image_id

    def get_available_tools(self) -> dict[str, Callable[..., Any]]:
        """Get the tools that are allowed to be used.

        Returns:
            A dictionary mapping tool names to their callable tool functions,
            filtered by the global ``tool_allow_list`` and ``tool_deny_list``.

        Note: This is a function instead of pre-computed in the constructor
        since the scenario extensions may modify the tool allow/deny lists,
        which would leave a pre-computed result out of sync.
        """
        return {
            name: tool
            for name, tool in self.name_to_tool.items()
            if (self.tool_allow_list is None or name in self.tool_allow_list)
            and (self.tool_deny_list is None or name not in self.tool_deny_list)
        }

    def get_available_tools_for_role(
        self, role_type: RoleType
    ) -> dict[str, Callable[..., Any]]:
        """Get the available tools for this role.

        Applies global allow/deny lists, role visibility, and per-role allow
        lists to filter the full tool set.

        For non-AGENT roles (e.g. USER), tools listed in the role-specific
        allow list are included even if the global ``tool_allow_list``
        (which controls agent-facing tools) does not contain them.  This
        ensures that user-only tools like ``send_message_with_image`` are
        available to the user simulator regardless of agent tool config.

        Args:
            role_type: The role to retrieve tools for.

        Returns:
            A dictionary mapping tool names to their callable tool functions,
            filtered by visibility and role-specific allow lists.
        """
        name_to_tool = self.get_available_tools()

        # For non-AGENT roles, add back tools that the role-specific allow
        # list requires but the global tool_allow_list excluded.
        if (
            role_type != RoleType.AGENT
            and role_type in self.role_tool_allow_list
            and self.tool_allow_list is not None
        ):
            allowed_names = set(self.role_tool_allow_list[role_type])
            for name, tool in self.name_to_tool.items():
                if name in allowed_names and name not in name_to_tool:
                    name_to_tool[name] = tool

        # Filter by visibility
        role_tools = {
            name: tool
            for name, tool in name_to_tool.items()
            if role_type in getattr(tool, "visible_to", (RoleType.AGENT,))
        }

        # Filter by role-specific allow list if present
        if role_type in self.role_tool_allow_list:
            allowed_names = set(self.role_tool_allow_list[role_type])
            role_tools = {
                name: tool for name, tool in role_tools.items() if name in allowed_names
            }

        return role_tools

    def _wrap_tool_for_execution(
        self, tool_name: str, tool_func: Callable[..., Any]
    ) -> Callable[..., Any]:
        """Wraps a tool function to update the LRU cache upon execution."""

        @functools.wraps(tool_func)
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            # Update LRU cache: move to the end (most recently used)
            if tool_name in self.active_tool_cache:
                self.active_tool_cache.remove(tool_name)
                self.active_tool_cache.append(tool_name)
            return tool_func(*args, **kwargs)

        return wrapper

    def register_tools(self, tool_names: list[str]) -> None:
        """Register tools for use in the execution environment.

        Implements an LRU cache to manage active tools in tool-search and
        hybrid modes.  New tools are added to the cache; if it exceeds
        ``MAX_ACTIVE_TOOLS``, the least recently used non-pinned tools are
        evicted.  Pinned tools (scenario-defined) are never evicted.

        In pure code-exec mode (``tool_allow_list is None``), all tools are
        pre-loaded — this method is a no-op.

        Updates:
        1. ``active_tool_cache``: LRU list of active tool names.
        2. ``interactive_console.locals``: Injects/removes tool functions.
        3. ``role_tool_allow_list``: Updates AGENT permissions.

        Args:
            tool_names: List of tool names to register.
        """
        # Pure code-exec: all tools permanently available, skip LRU.
        if self.tool_allow_list is None:
            return

        valid_tool_names = [name for name in tool_names if name in self.name_to_tool]
        if not valid_tool_names:
            return

        # Update global tool_allow_list
        for name in valid_tool_names:
            if name not in self.tool_allow_list:
                self.tool_allow_list.append(name)

        # Update LRU cache (most recently used at the end)
        for name in valid_tool_names:
            if name in self.active_tool_cache:
                self.active_tool_cache.remove(name)
            self.active_tool_cache.append(name)

        # Evict LRU tools if over capacity (pinned tools are never evicted)
        while len(self.active_tool_cache) > MAX_ACTIVE_TOOLS:
            evict_idx = next(
                (
                    i
                    for i, n in enumerate(self.active_tool_cache)
                    if n not in self.pinned_tools
                ),
                None,
            )
            if evict_idx is None:
                break
            evicted_tool = self.active_tool_cache.pop(evict_idx)
            if evicted_tool in self.interactive_console.locals:
                del cast(dict[str, Any], self.interactive_console.locals)[evicted_tool]
            if (
                RoleType.AGENT in self.role_tool_allow_list
                and evicted_tool in self.role_tool_allow_list[RoleType.AGENT]
            ):
                self.role_tool_allow_list[RoleType.AGENT].remove(evicted_tool)

        # Update locals with active tools
        # We re-inject all active tools to ensure they are present
        for name in self.active_tool_cache:
            tool = self.name_to_tool[name]
            wrapped_tool = self._wrap_tool_for_execution(name, tool)
            cast(dict[str, Any], self.interactive_console.locals)[name] = wrapped_tool

        # Update role_tool_allow_list for AGENT
        # We need to ensure the agent is allowed to call these tools.
        # Note: This assumes we are in a mode where role_tool_allow_list is being used
        # to restrict access (like Code Execution Mode).
        # IMPORTANT: We ONLY update role_tool_allow_list if it is already present for the AGENT.
        # If it is NOT present, it implies Standard Tool Use Mode where the agent has default access
        # (all tools or global tool_allow_list), and we should NOT inadvertently restrict it
        # by initializing an empty list.
        if RoleType.AGENT in self.role_tool_allow_list:
            current_allowed = set(self.role_tool_allow_list[RoleType.AGENT])
            current_allowed.update(self.active_tool_cache)
            self.role_tool_allow_list[RoleType.AGENT] = list(current_allowed)

    def to_dict(self, serialize_console: bool = True) -> dict[str, Any]:
        """Serializes to a dictionary

        We aim to make this serialization reversible, while still somewhat readable.

        Args:
            serialize_console:  If true, serialize interactive_console with dill. Note that this
                                cannot be dumped with json

        Returns:
            A serialized dict.
        """
        return {
            "_dbs": {
                namespace: database.to_dicts()
                for namespace, database in self._dbs.items()
            },
            "_introspection_dbs": self._introspection_db_manager.serialize_to_dict(),
            "interactive_console": dill.dumps(self.interactive_console)
            if serialize_console
            else None,
            "tool_allow_list": self.tool_allow_list,
            "role_tool_allow_list": {
                k.name: v for k, v in self.role_tool_allow_list.items()
            },
            "tool_deny_list": self.tool_deny_list,
            "trace_tool": self.trace_tool,
            "trace_nested_tool": self.trace_nested_tool,
            "toolbox": self.toolbox.serialize_to_dict(),
            "tool_state_registry": self.get_tool_state_registry().to_dict(),
            "active_tool_cache": self.active_tool_cache,
        }

    @classmethod
    def from_dict(cls, serialized_dict: dict[str, Any]) -> ExecutionContext:
        """Load a serialized dict produced by to_dict.

        Args:
            serialized_dict:    Serialized dict object.

        Returns:
            ExecutionContext object.
        """
        toolbox = Toolbox.deserialize_from_dict(serialized_dict["toolbox"])

        execution_context = cls(toolbox, delay_initialization=True)
        # Load _dbs
        for namespace in serialized_dict["_dbs"]:
            execution_context._dbs[DatabaseNamespace[namespace]] = pl.from_dicts(
                serialized_dict["_dbs"][namespace], schema=cls.dbs_schemas[namespace]
            )

        # The introspection databases have been added later so we make the loading
        # backwards compatible.
        serialized_intro_dbs = serialized_dict.get("_introspection_dbs", {})
        execution_context._introspection_db_manager = (
            IntrospectionDatabaseManager.deserialize_from_dict(serialized_intro_dbs)
        )

        # Load interactive_console
        execution_context.interactive_console = (
            dill.loads(serialized_dict["interactive_console"])
            if serialized_dict["interactive_console"] is not None
            else execution_context.interactive_console
        )
        # Load tool_allow_list
        execution_context.tool_allow_list = serialized_dict["tool_allow_list"]
        # Load role_tool_allow_list
        execution_context.role_tool_allow_list = {
            RoleType[k]: v
            for k, v in serialized_dict.get("role_tool_allow_list", {}).items()
        }
        # Load tool_deny_list
        execution_context.tool_deny_list = serialized_dict["tool_deny_list"]
        # Load trace_tool
        execution_context.trace_tool = serialized_dict["trace_tool"]
        # Load trace_nested_tool
        execution_context.trace_nested_tool = serialized_dict["trace_nested_tool"]

        # Load active_tool_cache
        execution_context.active_tool_cache = serialized_dict.get(
            "active_tool_cache", []
        )

        execution_context.execute_delayed_initialization()

        # Now that we have performed the delayed initialization we can check the tool
        # state registry consistency.
        serialized_tool_state_registry = serialized_dict.get("tool_state_registry")
        if serialized_tool_state_registry is not None:
            execution_context.get_tool_state_registry().check_consistency(
                serialized_tool_state_registry
            )

        return execution_context

    @classmethod
    def from_json_file(cls, path: pathlib.Path) -> ExecutionContext:
        """Deserialize an ``ExecutionContext`` from a JSON file.

        Args:
            path: Path to a JSON file produced by serializing ``to_dict()``.

        Returns:
            A restored ``ExecutionContext`` instance.
        """
        serialized_dict = json.load(path.open("rt"))
        return cls.from_dict(serialized_dict)

    def __deepcopy__(self, memo: dict[int, Any]) -> ExecutionContext:
        # The `InteractiveConsole` is not copyable/picklable with the Python standard
        # library. `dill` adds support for pickling additional Python objects so it can
        # successfully copy an `InteractiveConsole`. Note that `dill.copy` performs a
        # deep copy.
        return cast(ExecutionContext, dill.copy(self))

    @staticmethod
    def headguard_predicate(column_names: set[str]) -> pl.Expr:
        """A polars expression matching headguard rows

        Specifically this looks for rows where all columns expect "sandbox_message_index" are None

        Args:
            column_names:   Column names in the dataframe
        Returns:
            A polars expression matching headguard rows
        """
        # Hacky way to make bitwise and work in a loop
        return pl.lit(True).and_(
            *[
                pl.col(column_name).is_null()
                for column_name in (column_names - {"sandbox_message_index"})
            ]
        )

    @classmethod
    def drop_headguard(cls, dataframe: pl.DataFrame) -> pl.DataFrame:
        """Drops the all None headguard row

        Args:
            dataframe:  Dataframe to drop headguard row from. Usually a snapshot or multiple snapshots

        Returns:
            Dataframe with headguard dropped.
        """
        return dataframe.filter(
            ~cls.headguard_predicate(column_names=set(dataframe.columns))
        )

    @property
    def max_sandbox_message_index(self) -> int:
        """Get the current max_sandbox_index, returns -1 when no messages exist."""
        series = self.drop_headguard(self._dbs[DatabaseNamespace.SANDBOX]).get_column(
            "sandbox_message_index"
        )
        if series.is_empty():
            return -1
        return cast(int, series.max())

    @property
    def first_user_sandbox_message_index(self) -> int:
        """Index of the first USER→AGENT message in the SANDBOX database.

        The database snapshot at this index defines the starting world state
        used by the evaluation pipeline (entity diff, judge evidence).

        Returns -1 if no user message was found.
        """
        user_messages_db: pl.DataFrame = self.get_database(
            namespace=DatabaseNamespace.SANDBOX,
            get_all_history_snapshots=True,
            drop_sandbox_message_index=False,
        ).filter(
            (pl.col("sender") == RoleType.USER)
            & (
                (pl.col("visible_to") != [RoleType.USER])
                | (pl.col("visible_to").is_null())
            )
        )
        if user_messages_db.is_empty():
            return -1
        return cast(int, user_messages_db["sandbox_message_index"][0])

    def get_most_recent_snapshot_sandbox_message_index(
        self, namespace: DatabaseNamespace, query_index: int
    ) -> int:
        """Find sandbox_message_index corresponding to the most recent snapshot no later than query_index

        Args:
            namespace:      Namespace to search under
            query_index:    Query index

        Returns:
            Target index

        Raises:
            IndexError:     When query_index is larger than the largest available sandbox_message_index in Sandbox DB
        """
        # When the database is empty, default to 0. This will cause us to copy
        # default headguard at index 0.
        if self.drop_headguard(self._dbs[namespace]).is_empty():
            return 0
        snapshot_indices = (
            self._dbs[namespace].get_column("sandbox_message_index").unique()
        ).sort()
        # Maximum legal index for any database to have is max_sandbox + 1. Since database could be adding entry
        # corresponding to the current message being processed, which haven't been added to the SANDBOX database
        max_index = self.max_sandbox_message_index + 1
        if query_index > max_index:
            raise IndexError(
                f"{query_index=} is larger than the largest available "
                f"sandbox_message_index + 1 = {max_index} in Sandbox DB."
            )
        # Find most recent snapshot no later than query_index
        # If out of bounds, default to first available snapshot, which should always be 0 due to default headguard
        idx = snapshot_indices[
            max((bisect.bisect(a=snapshot_indices, x=query_index) - 1), 0)
        ]
        return cast(int, idx)

    def _maybe_create_snapshot(self, namespace: DatabaseNamespace) -> None:
        """If db snapshot under namespace that links to max_sandbox_message_index + 1 doesn't exist, create one

        Args:
            namespace:                      Namespace to create snapshot under
        """
        if namespace not in self._dbs:
            return
        max_sandbox_message_index = self.max_sandbox_message_index
        if (
            self._dbs[namespace]
            .filter(pl.col("sandbox_message_index") == max_sandbox_message_index + 1)
            .is_empty()
        ):
            most_recent_index = self.get_most_recent_snapshot_sandbox_message_index(
                namespace, max_sandbox_message_index
            )
            most_recent_snapshot = self._dbs[namespace].filter(
                pl.col("sandbox_message_index") == most_recent_index
            )
            # Update sandbox_message_index and stack the new snapshot at the end of database
            self._dbs[namespace] = self._dbs[namespace].vstack(
                most_recent_snapshot.with_columns(
                    pl.when(pl.col("sandbox_message_index") == most_recent_index)
                    .then(max_sandbox_message_index + 1)
                    .alias("sandbox_message_index")
                )
            )

    def get_database(
        self,
        namespace: DatabaseNamespace,
        sandbox_message_index: int | None = None,
        get_all_history_snapshots: bool = False,
        drop_sandbox_message_index: bool = True,
        drop_headguard: bool = True,
    ) -> pl.DataFrame:
        """Get a database given the namespace and sandbox_message_index

        By default, gets the most recent database snapshot. When sandbox_message_index is provided,
        find the most recent snapshot no later than sandbox_message_index

        When get_all_history_snapshots is True, return all snapshots <= sandbox_message_index, this is useful for
        accessing message history

        Note that the database returned is a subview of the original database. Please treat it as an immutable object
        to avoid unintended effect. Use add / remove functions to modify database if needed.

        Args:
            namespace:                  Database namespace
            sandbox_message_index:      Which message this database corresponds to
            get_all_history_snapshots:  Return all entries where snapshot index <= sandbox_message_index
            drop_sandbox_message_index: Drop the drop_sandbox_message_index column or not, defaults to True
            drop_headguard:             Drop the null headguard entry. Should only be turned off for debugging purposes

        Returns:
            Requested snapshot of database

        Raises:
            IndexError: When sandbox_message_index is larger than the largest available sandbox_message_index in
                        Sandbox DB
        """
        if sandbox_message_index is None:
            sandbox_message_index = self.max_sandbox_message_index + 1
        snapshot_target_index = self.get_most_recent_snapshot_sandbox_message_index(
            namespace, sandbox_message_index
        )
        predicate = (
            pl.col("sandbox_message_index") <= snapshot_target_index
            if get_all_history_snapshots
            else pl.col("sandbox_message_index") == snapshot_target_index
        )
        dataframe = self._dbs[namespace].filter(predicate)
        if drop_sandbox_message_index:
            dataframe = dataframe.drop("sandbox_message_index")
        if drop_headguard:
            dataframe = self.drop_headguard(dataframe)
        return dataframe

    def add_to_introspection_database(
        self,
        namespace: IntrospectionDatabaseNamespace,
        rows: list[dict[str, Any]],
    ) -> None:
        """Add multiple rows to an introspection database.

        Args:
            namespace:  Database namespace
            rows:  List of rows to be added. Each item must be a dict mapping from
                   column name to value.

        Raises:
            KeyError:   When provided column names in rows do not match the schema.

        """
        self._introspection_db_manager.add(
            namespace=namespace,
            rows=rows,
            sandbox_message_index=self.max_sandbox_message_index,
        )

    def add_to_database(
        self,
        namespace: DatabaseNamespace,
        rows: list[dict[str, Any]],
    ) -> None:
        """Add multiple rows to a database

        If namespace != SANDBOX:

        Assumes that the operation is the outcome of a message that's being processed (because all messages
        already committed to the database are have finished execution). Which means we will create a snapshot if
        the snapshot doesn't exist, and start operating on this snapshot.

        If namespace == SANDBOX:

        Add the messages to SANDBOX table and increment index

        Args:
            namespace:                      Database namespace
            rows:                           List of rows to be added, each item should be a Dict of column and value

        Raises:
            KeyError:   When provided column names in rows does not match given schema
            ValueError: When entry is all None. All None is reserved for headguard

        """
        # Check if column name in rows are found in namespace schema
        rows_column_names = {x for row in rows for x in row.keys()}
        schema_column_names = set(self.dbs_schemas[namespace].keys())
        if rows_column_names - schema_column_names:
            raise KeyError(
                f"Only column names {schema_column_names} are allowed for namespace {namespace}. "
                f"Found unknown column name {rows_column_names - schema_column_names}"
            )
        # Check if values are all None in some rows
        for row in rows:
            if all(
                row[column_name] is None if column_name in row else True
                for column_name in schema_column_names - {"sandbox_message_index"}
            ):
                raise ValueError(
                    "Cannot add row with all None values. All None values are reserved for headguard"
                )
        rows = copy.deepcopy(rows)
        if namespace != DatabaseNamespace.SANDBOX:
            self._maybe_create_snapshot(namespace)
            # Add sandbox_message_index to rows
            for row in rows:
                row["sandbox_message_index"] = self.max_sandbox_message_index + 1
        else:
            # Carry over previous conversation_active if not provided and add message index
            previous_conversation_active = (
                True
                if self.get_database(DatabaseNamespace.SANDBOX).is_empty()
                else self.get_database(DatabaseNamespace.SANDBOX)[
                    "conversation_active"
                ][-1]
            )
            current_sandbox_message_index = self.max_sandbox_message_index + 1
            for row in rows:
                row["sandbox_message_index"] = current_sandbox_message_index
                if (
                    "conversation_active" not in row
                    or row["conversation_active"] is None
                ):
                    row["conversation_active"] = previous_conversation_active
                previous_conversation_active = row["conversation_active"]
                current_sandbox_message_index += 1
        if namespace in self._dbs:
            self._dbs[namespace] = self._dbs[namespace].vstack(
                pl.DataFrame(rows, schema=self.dbs_schemas[namespace])
            )

    def remove_from_database(
        self,
        namespace: DatabaseNamespace,
        predicate: IntoExprColumn,
        allow_no_match: bool = False,
    ) -> None:
        """Remove multiple rows from a database

        Assumes that the operation is the outcome of a message that's being processed (because all messages
        already committed to the database are have finished execution). Which means we will create a snapshot if
        the snapshot doesn't exist, and start operating on this snapshot.

        Args:
            namespace:      Database namespace
            predicate:      A polars predicate that evaluates to boolean, used to identify the rows to remove
            allow_no_match:    If true, allows predicate not to match any entries.

        Raises:
            NoDataError:            If no matching rows where found
            KeyError:               When attempting to remove entry from SANDBOX database
        """
        if namespace == DatabaseNamespace.SANDBOX:
            raise KeyError("Removal from SANDBOX database is not allowed")
        sandbox_message_index = self.max_sandbox_message_index + 1
        self._maybe_create_snapshot(namespace)
        # Add sandbox_message_index predicate
        predicate_idx = pl.col("sandbox_message_index") == sandbox_message_index
        predicate &= predicate_idx
        if self._dbs[namespace].filter(predicate).is_empty():
            if allow_no_match:
                return
            raise NoDataError(f"No db entry matching {predicate=} found")
        # Remove entries that match predicate, except for headguard
        self._dbs[namespace] = self._dbs[namespace].filter(
            ~predicate
            | self.headguard_predicate(column_names=set(self._dbs[namespace].columns))
        )
        # If current context has no entries, add a null entry (to avoid snapshot overwriting this)...
        if self._dbs[namespace].filter(predicate_idx).is_empty():
            self._dbs[namespace] = self._dbs[namespace].vstack(
                self._make_null_df(namespace, idx=sandbox_message_index)
            )

    def update_database(
        self,
        namespace: DatabaseNamespace,
        dataframe: pl.DataFrame,
    ) -> None:
        """Update the current database snapshot

        When simple add / remove is not sufficient, allows user to provide a new dataframe to replace the
        most recent snapshot. sandbox_message_index is overridden based on existing snapshot index

        Args:
            namespace:      Database namespace
            dataframe:      Dataframe to replace the existing snapshot
        """
        if namespace != DatabaseNamespace.SANDBOX:
            self._maybe_create_snapshot(namespace)
            sandbox_message_index = self.max_sandbox_message_index + 1
        else:
            # Sandbox database update points to the most recent message
            sandbox_message_index = self.max_sandbox_message_index
        # Add sandbox_message_index to dataframe
        dataframe = dataframe.with_columns(
            pl.lit(sandbox_message_index, dtype=pl.Int32).alias("sandbox_message_index")
        ).select(self._dbs[namespace].columns)
        # Add headguard if it's not provided already
        dataframe = self._make_null_df(namespace, idx=sandbox_message_index).vstack(
            self.drop_headguard(dataframe)
        )
        # Update database
        self._dbs[namespace] = (
            self._dbs[namespace]
            .filter(pl.col("sandbox_message_index") != sandbox_message_index)
            .vstack(dataframe)
        )


def _set_global_execution_context_for_thread(
    thread_id: int, execution_context: ExecutionContext
) -> ExecutionContext:
    """Set up the global execution context.

    This is a workaround for the circular dependency between `ExecutionContext` and
    `mmtoolsandbox.tools`. More specifically, inside `ExecutionContext.__init__` we
    gather the tools exposed in `mmtoolsandbox.tools`. Thus, we cannot just use
       _global_execution_context[threading.get_ident()] = ExecutionContext()
    at the module level since it would trigger the circular dependency. So what we are
    doing here is a lazily evaluated global variable following
    https://stackoverflow.com/a/54616590 .

    Implements thread safety by assigning individual ExecutionContext to each thread.

    """
    if globals().get("_global_execution_context") is None:
        globals()["_global_execution_context"] = {}
    globals()["_global_execution_context"][thread_id] = execution_context
    return execution_context


def get_current_context() -> ExecutionContext:
    """Getter for global execution context variable. Each thread has its own execution context.

    Returns:
        Global execution context object.

    """
    # Just doing `global _global_execution_context` caused some tests to fail when
    # running them in parallel using pytest-xdist. The error was:
    #   NameError: name '_global_execution_context' is not defined
    # This has to do with how xdist executes the tests in different processes. As a
    # simple workaround we explicitly check if the global variable exists here and if
    # not we create it.
    thread_id: int = threading.get_ident()
    global_execution_context = globals().get("_global_execution_context")
    # If execution_context for thread doesn't exist, init.
    if (
        global_execution_context is None
        or global_execution_context.get(thread_id) is None
    ):
        return _set_global_execution_context_for_thread(
            thread_id=thread_id, execution_context=ExecutionContext()
        )
    return cast(ExecutionContext, globals()["_global_execution_context"][thread_id])


def set_current_context(execution_context: ExecutionContext) -> None:
    """Setter for global execution context variable. Each thread has its own execution context.

    Args:
        execution_context: new context to be applied as global execution context
    """
    _set_global_execution_context_for_thread(
        thread_id=threading.get_ident(), execution_context=execution_context
    )


@contextlib.contextmanager
def new_context(context: ExecutionContext) -> Iterator[ExecutionContext]:
    """Handy context manager which patches _global_execution_context with context, and reverts after context exit

    Args:
        context:    Context to apply

    Yields:
        The supplied ExecutionContext.
    """
    original_context = get_current_context()
    try:
        set_current_context(context)
        yield context
    # Release resource even when exceptions are raised
    finally:
        # Reset original context
        set_current_context(original_context)


@contextlib.contextmanager
def new_context_with_attribute(**kwargs: Any) -> Iterator[ExecutionContext]:
    """Handy context manager which modifies _global_execution_context given new attributes listed in kwargs,
    and reverts after context exit

    Args:
        **kwargs:       Attribute name and values to override in _global_execution_context

    Yields:
        The modified ExecutionContext.
    """
    original_context = get_current_context()
    # Make sure all attributes exist
    for attribute_name, value in kwargs.items():
        if not hasattr(original_context, attribute_name):
            raise AttributeError(
                f"Execution context does not contain attribute of name {attribute_name}"
            )
    # Gather original attributes
    original_attributes = {
        attribute_name: getattr(original_context, attribute_name)
        for attribute_name in kwargs
    }
    try:
        for attribute_name, value in kwargs.items():
            setattr(original_context, attribute_name, value)
        yield original_context
    # Release resource even when exceptions are raised
    finally:
        # Reset original context
        for attribute_name, value in original_attributes.items():
            setattr(original_context, attribute_name, value)


def get_locale() -> Locale | None:
    """Return the locale from the current context's SETTING database.

    Reads the first row of the SETTING database to determine the active
    locale.

    Returns:
        The ``Locale`` enum value, or ``None`` if the locale is not set.
    """
    setting_database = get_current_context().get_database(DatabaseNamespace.SETTING)
    locale = setting_database["locale"][0]

    if locale:
        return Locale[locale]

    return None
