"""
Amazon API tools for MMToolSandbox.

This module wraps AppWorld's Amazon APIs as MMToolSandbox-compatible tools
with state dependency checks (network, authentication).

Auto-generated by generate_static_wrappers.py
"""

from typing import Any

from mmtoolsandbox.appworld.bridge import get_appworld_bridge
from mmtoolsandbox.appworld.state import (
    get_appworld_state,
    requires_auth,
    requires_network,
)
from mmtoolsandbox.tools.appworld import register_appworld_tool


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_account() -> dict[str, Any]:
    """
    Show your account information. Unlike show_profile, this includes private information.

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime), "last_logged_in": str (datetime), "track_browsing_history": bool, "verified": bool, "is_prime": bool}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "show_account", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_signup(
    first_name: str, last_name: str, email: str, password: str
) -> dict[str, Any]:
    """
    Sign up to create account.

    Args:
        first_name: Your first name. Minimum length: 1.
        last_name: Your last name. Minimum length: 1.
        email: Your email address. Must be a valid email address.
        password: Your password. Minimum length: 5.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "first_name": first_name,
        "last_name": last_name,
        "email": email,
        "password": password,
    }

    response = bridge.call_api("amazon", "signup", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_delete_account() -> dict[str, Any]:
    """
    Delete your account.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "delete_account", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_account_name(
    first_name: str | None = None, last_name: str | None = None
) -> dict[str, Any]:
    """
    Update your first or last name in the account profile.

    Args:
        first_name: Your updated first name. Minimum length: 1. (optional)
        last_name: Your updated last name. Minimum length: 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }
    if first_name is not None:
        params["first_name"] = first_name
    if last_name is not None:
        params["last_name"] = last_name

    response = bridge.call_api(
        "amazon", "update_account_name", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_login(username: str, password: str) -> dict[str, Any]:
    """
    Login to your account.

    Args:
        username: Your account email.
        password: Your account password.

    Returns:
        Success: {"access_token": str, "token_type": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "username": username,
        "password": password,
    }

    response = bridge.call_api("amazon", "login", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Register login state
    if isinstance(response, dict) and "access_token" in response:
        appworld_state.login(
            "amazon", response["access_token"], response.get("user_id")
        )

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_logout() -> dict[str, Any]:
    """
    Logout from your account.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "logout", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_send_verification_code(email: str) -> dict[str, Any]:
    """
    Send account verification code to your email address.

    Args:
        email: Your email address. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
    }

    response = bridge.call_api(
        "amazon", "send_verification_code", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_verify_account(email: str, verification_code: str) -> dict[str, Any]:
    """
    Verify your account using the verification code sent to your email address.

    Args:
        email: Your email address. Must be a valid email address.
        verification_code: The verification code sent to your email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
        "verification_code": verification_code,
    }

    response = bridge.call_api("amazon", "verify_account", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_send_password_reset_code(email: str) -> dict[str, Any]:
    """
    Send password reset code to your email address.

    Args:
        email: Your email address. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
    }

    response = bridge.call_api(
        "amazon", "send_password_reset_code", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_reset_password(
    email: str, password_reset_code: str, new_password: str
) -> dict[str, Any]:
    """
    Reset your password using the password reset code sent to your email address.

    Args:
        email: Your email address. Must be a valid email address.
        password_reset_code: The password reset code sent to your email address.
        new_password: Your new password. Minimum length: 5.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
        "password_reset_code": password_reset_code,
        "new_password": new_password,
    }

    response = bridge.call_api("amazon", "reset_password", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_show_profile(email: str | None = None) -> dict[str, Any]:
    """
    Show public profile information of a user.

    Args:
        email: Email of the person you want to see the profile information of. Must be a valid email address. (optional)

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime)}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if email is not None:
        params["email"] = email

    response = bridge.call_api("amazon", "show_profile", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_show_product(product_id: int) -> dict[str, Any]:
    """
    Show product information based on its ID.

    Args:
        product_id: The ID of the product.

    Returns:
        Success: {"product_id": int, "seller_id": int, "product_type": str, "name": str, "description": str, "price": float, "delivery_days": float, "inventory_quantity": float, ...}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "product_id": product_id,
    }

    response = bridge.call_api("amazon", "show_product", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_recommended_products(
    page_index: int | None = 0, page_limit: int | None = 5
) -> list[dict[str, Any]]:
    """
    Show products recommended for you.

    Args:
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"product_id": int, "seller_id": int, "product_type": str, "name": str, "description": str, "price": float, "delivery_days": float, "inventory_quantity": float, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api(
        "amazon", "show_recommended_products", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_browsing_history(
    page_index: int | None = 0, page_limit: int | None = 5
) -> list[dict[str, Any]]:
    """
    Show products in your browsing history.

    Args:
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"product_id": int, "seller_id": int, "product_type": str, "name": str, "description": str, "price": float, "delivery_days": float, "inventory_quantity": float, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api(
        "amazon", "show_browsing_history", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_clear_browsing_history() -> dict[str, Any]:
    """
    Clear your browsing history.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api(
        "amazon", "clear_browsing_history", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_add_product_to_browsing_history(product_id: int) -> dict[str, Any]:
    """
    Add a product to your browsing history.

    Args:
        product_id: ID of the product to add to browsing history.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }

    response = bridge.call_api(
        "amazon", "add_product_to_browsing_history", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_remove_product_from_browsing_history(product_id: int) -> dict[str, Any]:
    """
    Remove a product from your browsing history.

    Args:
        product_id: ID of the product to remove from browsing history.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }

    response = bridge.call_api(
        "amazon", "remove_product_from_browsing_history", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_browsing_history_tracking(
    track_browsing_history: bool,
) -> dict[str, Any]:
    """
    Update browsing history tracking preference.

    Args:
        track_browsing_history: Whether to track browsing history.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "track_browsing_history": track_browsing_history,
    }

    response = bridge.call_api(
        "amazon", "update_browsing_history_tracking", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_last_product_purchase(product_id: int) -> dict[str, Any]:
    """
    Show your last purchase information of a product with the given ID or its size and color variations.

    Args:
        product_id: The ID of the product.

    Returns:
        Success: {"order_id": int, "ordered_at": str (datetime), "product_id": int, "product_name": str, "product_relative_size": str, "product_color": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }

    response = bridge.call_api(
        "amazon", "show_last_product_purchase", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_show_product_rating_distribution(product_id: int) -> dict[str, Any]:
    """
    Show the rating distribution of a product.

    Args:
        product_id: The ID of the product.

    Returns:
        Success: {"rating": float, "num_product_reviews": int, "breakdown": list[dict]}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "product_id": product_id,
    }

    response = bridge.call_api(
        "amazon", "show_product_rating_distribution", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_search_sellers(
    query: str | None = "",
    page_index: int | None = 0,
    page_limit: int | None = 5,
) -> list[dict[str, Any]]:
    """
    Search for sellers with a query.

    Args:
        query: The search query string. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"seller_id": int, "name": str}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if query is not None:
        params["query"] = query
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api("amazon", "search_sellers", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
def amazon_show_seller(seller_id: int) -> dict[str, Any]:
    """
    Show a detailed information about the seller.

    Args:
        seller_id: The ID of the seller.

    Returns:
        Success: {"seller_id": int, "name": str, "rating": float}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "seller_id": seller_id,
    }

    response = bridge.call_api("amazon", "show_seller", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_search_product_types(
    query: str | None = "",
    page_index: int | None = 0,
    page_limit: int | None = 5,
) -> list[dict[str, Any]]:
    """
    Search product types present in the database.

    Args:
        query: The search query string. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be >= 1. (optional)

    Returns:
        Success: [str]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if query is not None:
        params["query"] = query
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api("amazon", "search_product_types", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
def amazon_show_product_feature_choices(
    product_type: str | None = None,
) -> dict[str, Any]:
    """
    Show the choices of colors, relative sizes and sellers aggregated over all products of the given product type. Because it's an aggregation, the choices may not be available for all products. If product type is not passed, it will return the choices for all products in the database.

    Args:
        product_type: The product type to obtain feature choices for. (optional)

    Returns:
        Success: {"colors": list[str], "relative_sizes": list[str], "sellers": list[dict]}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if product_type is not None:
        params["product_type"] = product_type

    response = bridge.call_api(
        "amazon", "show_product_feature_choices", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_search_products(
    query: str | None = "",
    product_type: str | None = None,
    color: str | None = None,
    relative_size: str | None = None,
    min_price: float | None = 0.0,
    max_price: float | None = 9.223372036854776e18,
    min_product_rating: float | None = 0.0,
    max_product_rating: float | None = 5.0,
    min_seller_rating: float | None = 0.0,
    max_seller_rating: float | None = 5.0,
    seller_id: int | None = None,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Search for products with a query and various filtering criteria.

    Args:
        query: The search query string. (optional)
        product_type: The type of product to search for. (optional)
        color: The color of product to search for. (optional)
        relative_size: The relative size of product to search for. Must be one of: 'extra-small', 'small', 'medium', 'large', 'extra-large'. (optional)
        min_price: The minimum price for search results. Must be >= 0.0. (optional)
        max_price: The maximum price for search results. Must be >= 0.0. (optional)
        min_product_rating: The minimum product rating for search results. Must be between 0.0 and 5.0. (optional)
        max_product_rating: The maximum product rating for search results. Must be between 0.0 and 5.0. (optional)
        min_seller_rating: The minimum seller rating for search results. Must be between 0.0 and 5.0. (optional)
        max_seller_rating: The maximum seller rating for search results. Must be between 0.0 and 5.0. (optional)
        seller_id: ID of the seller to search for. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the products by prefixed with +/- to reflect ascending/descending. Valid attributes: rating, price and delivery_days. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. (optional)

    Returns:
        Success: [{"product_id": int, "seller_id": int, "product_type": str, "name": str, "description": str, "price": float, "delivery_days": float, "inventory_quantity": float, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if query is not None:
        params["query"] = query
    if product_type is not None:
        params["product_type"] = product_type
    if color is not None:
        params["color"] = color
    if relative_size is not None:
        params["relative_size"] = relative_size
    if min_price is not None:
        params["min_price"] = min_price
    if max_price is not None:
        params["max_price"] = max_price
    if min_product_rating is not None:
        params["min_product_rating"] = min_product_rating
    if max_product_rating is not None:
        params["max_product_rating"] = max_product_rating
    if min_seller_rating is not None:
        params["min_seller_rating"] = min_seller_rating
    if max_seller_rating is not None:
        params["max_seller_rating"] = max_seller_rating
    if seller_id is not None:
        params["seller_id"] = seller_id
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("amazon", "search_products", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_cart() -> dict[str, Any]:
    """
    show your cart.

    Returns:
        Success: {"delivery_fee": float, "base_cost": float, "tax": float, "gift_wrap_fee": float, "discount": float, "total_cost": float, "promo_code": str, "promo_valid": bool, ...}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "show_cart", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_clear_cart() -> dict[str, Any]:
    """
    Clear your cart.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "clear_cart", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_add_product_to_cart(
    product_id: int,
    quantity: int = 1,
    clear_cart_first: bool | None = False,
) -> dict[str, Any]:
    """
    Add product by id and quantities to your cart.

    Args:
        product_id: ID of the product to be added to the cart.
        quantity: The quantity of the product to be added to the cart. Defaults to 1. Must be >= 1.
        clear_cart_first: If true, the cart will be cleared before adding the product to the cart. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
        "quantity": quantity,
    }
    if clear_cart_first is not None:
        params["clear_cart_first"] = clear_cart_first

    response = bridge.call_api("amazon", "add_product_to_cart", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_product_quantity_in_cart(
    product_id: int, quantity: int
) -> dict[str, Any]:
    """
    Update product quantity in the user cart.

    Args:
        product_id: ID of the product to be updated in the cart.
        quantity: The new quantity of the product to be updated in the cart. Must be >= 0.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
        "quantity": quantity,
    }

    response = bridge.call_api(
        "amazon", "update_product_quantity_in_cart", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_delete_product_from_cart(product_id: int) -> dict[str, Any]:
    """
    Remove a product from your cart.

    Args:
        product_id: ID of the product to be deleted from the cart.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }

    response = bridge.call_api(
        "amazon", "delete_product_from_cart", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_apply_promo_code_to_cart(promo_code: str) -> dict[str, Any]:
    """
    Apply a promo code to your cart.

    Args:
        promo_code: The promo code to be applied to the cart.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "promo_code": promo_code,
    }

    response = bridge.call_api(
        "amazon", "apply_promo_code_to_cart", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_remove_promo_code_from_cart() -> dict[str, Any]:
    """
    Remove a promo code from your cart.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api(
        "amazon", "remove_promo_code_from_cart", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_wish_list() -> list[dict[str, Any]]:
    """
    Get list of products in your wishlist.

    Returns:
        Success: [{"product_id": int, "product_name": str, "product_type": str, "rating": float, "relative_size": str, "color": str, "quantity": float, "price": float, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "show_wish_list", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_clear_wish_list() -> dict[str, Any]:
    """
    Clear wish list.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "clear_wish_list", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_add_product_to_wish_list(
    product_id: int,
    quantity: int = 1,
    clear_wish_list_first: bool | None = False,
) -> dict[str, Any]:
    """
    Add product by id and quantities to your wish list.

    Args:
        product_id: ID of the product to be added to the wish list.
        quantity: The quantity of the product to be added to the wish list. Defaults to 1. Must be >= 1.
        clear_wish_list_first: If true, the wish list will be cleared before adding the product to the wish list. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
        "quantity": quantity,
    }
    if clear_wish_list_first is not None:
        params["clear_wish_list_first"] = clear_wish_list_first

    response = bridge.call_api(
        "amazon", "add_product_to_wish_list", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_delete_product_from_wish_list(product_id: int) -> dict[str, Any]:
    """
    Remove product from the user wish list.

    Args:
        product_id: ID of the product to be deleted from the wish list.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }

    response = bridge.call_api(
        "amazon", "delete_product_from_wish_list", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_product_quantity_in_wish_list(
    product_id: int, quantity: int
) -> dict[str, Any]:
    """
    Update product quantity in the user wish_list.

    Args:
        product_id: ID of the product being updated in the wish list.
        quantity: The new quantity of the product to be updated in the wish list. Must be >= 0.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
        "quantity": quantity,
    }

    response = bridge.call_api(
        "amazon", "update_product_quantity_in_wish_list", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_move_product_from_cart_to_wish_list(
    product_id: int, quantity: int | None = 1
) -> dict[str, Any]:
    """
    Move product from the cart to the wish list.

    Args:
        product_id: ID of the product to be move
        quantity: Quantity of the product to move. Must be >= 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }
    if quantity is not None:
        params["quantity"] = quantity

    response = bridge.call_api(
        "amazon", "move_product_from_cart_to_wish_list", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_move_product_from_wish_list_to_cart(
    product_id: int, quantity: int | None = 1
) -> dict[str, Any]:
    """
    Move product from the wish list to the cart.

    Args:
        product_id: ID of the product to move to cart.
        quantity: Quantity of product to move to cart. Must be >= 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }
    if quantity is not None:
        params["quantity"] = quantity

    response = bridge.call_api(
        "amazon", "move_product_from_wish_list_to_cart", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_add_gift_wrapping_to_product(
    product_id: int, quantity: int | None = 1
) -> dict[str, Any]:
    """
    Add gift wrapping to a product in your cart. If the product is already set to be gift wrapped, its quantity will be updated.

    Args:
        product_id: ID of the product in your cart to be gift wrapped.
        quantity: Quantity of the product to be gift wrapped. Must be >= 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }
    if quantity is not None:
        params["quantity"] = quantity

    response = bridge.call_api(
        "amazon", "add_gift_wrapping_to_product", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_remove_gift_wrapping_from_product(product_id: int) -> dict[str, Any]:
    """
    Remove gift wrapping from a product in your cart.

    Args:
        product_id: ID of the product in your cart to be gift wrapped.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
    }

    response = bridge.call_api(
        "amazon", "remove_gift_wrapping_from_product", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_orders(
    query: str | None = "",
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search your past orders

    Args:
        query: Search query string. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the orders by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -created_at. (optional)

    Returns:
        Success: [{"order_id": int, "address_id": int, "payment_card_id": int, "tax": float, "delivery_fee": float, "gift_wrap_fee": float, "discount": float, "created_at": str (datetime), ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }
    if query is not None:
        params["query"] = query
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("amazon", "show_orders", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_place_order(payment_card_id: int, address_id: int) -> dict[str, Any]:
    """
    Place an order for all the items in your cart.

    Args:
        payment_card_id: ID of the payment card to use for this order.
        address_id: ID of the address used for shipping this order.

    Returns:
        Success: {"message": str, "order_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "payment_card_id": payment_card_id,
        "address_id": address_id,
    }

    response = bridge.call_api("amazon", "place_order", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_product_purchases(
    page_index: int | None = 0, page_limit: int | None = 5
) -> list[dict[str, Any]]:
    """
    Show products you have purchased in the past.

    Args:
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"product_id": int, "seller_id": int, "product_type": str, "name": str, "description": str, "price": float, "delivery_days": float, "inventory_quantity": float, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api(
        "amazon", "show_product_purchases", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_order(order_id: int) -> dict[str, Any]:
    """
    Get details of a past order.

    Args:
        order_id: ID of the order to be shown.

    Returns:
        Success: {"order_id": int, "address_id": int, "payment_card_id": int, "tax": float, "delivery_fee": float, "gift_wrap_fee": float, "discount": float, "created_at": str (datetime), ...}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "order_id": order_id,
    }

    response = bridge.call_api("amazon", "show_order", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_download_order_receipt(
    order_id: int,
    file_system_access_token: str,
    download_to_file_path: str | None = None,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Download the receipt of a past order.

    Args:
        order_id: ID of the order to download the receipt for.
        file_system_access_token: Access token obtained from file_system app login.
        download_to_file_path: The file path to download the receipt file to in file system app. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. If not passed, it will be saved in your ~/downloads directory. (optional)
        overwrite: Whether to overwrite the file if it already exists. (optional)

    Returns:
        Success: {"message": str, "file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "order_id": order_id,
        "file_system_access_token": file_system_access_token,
    }
    if download_to_file_path is not None:
        params["download_to_file_path"] = download_to_file_path
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api(
        "amazon", "download_order_receipt", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_payment_cards() -> list[dict[str, Any]]:
    """
    Get a list of your payment cards.

    Returns:
        Success: [{"payment_card_id": int, "card_name": str, "owner_name": str, "card_number": float, "expiry_year": int, "expiry_month": float, "cvv_number": float}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "show_payment_cards", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_add_payment_card(
    card_name: str,
    owner_name: str,
    card_number: int,
    expiry_year: int,
    expiry_month: int,
    cvv_number: int,
) -> dict[str, Any]:
    """
    Add a new payment card.

    Args:
        card_name: Name of the payment card. Minimum length: 1.
        owner_name: Full name of the owner of the payment card. Minimum length: 1.
        card_number: 16-digit card number. Must be >= 1000000000000000.
        expiry_year: Expiration year of the payment card.
        expiry_month: Expiration month of the payment card. Must be between 1 and 12.
        cvv_number: A 3-digit CVV number of the payment card. Must be >= 100 and < 1000.

    Returns:
        Success: {"message": str, "payment_card_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "card_name": card_name,
        "owner_name": owner_name,
        "card_number": card_number,
        "expiry_year": expiry_year,
        "expiry_month": expiry_month,
        "cvv_number": cvv_number,
    }

    response = bridge.call_api("amazon", "add_payment_card", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_payment_card(payment_card_id: int) -> dict[str, Any]:
    """
    Get details of a payment card.

    Args:
        payment_card_id: ID of the payment card to be shown.

    Returns:
        Success: {"payment_card_id": int, "card_name": str, "owner_name": str, "card_number": float, "expiry_year": int, "expiry_month": float, "cvv_number": float}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "payment_card_id": payment_card_id,
    }

    response = bridge.call_api("amazon", "show_payment_card", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_payment_card(payment_card_id: int, card_name: str) -> dict[str, Any]:
    """
    Update payment card information.

    Args:
        payment_card_id: ID of the payment card to update.
        card_name: Name of the payment card to update. Minimum length: 1.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "payment_card_id": payment_card_id,
        "card_name": card_name,
    }

    response = bridge.call_api(
        "amazon", "update_payment_card", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_delete_payment_card(payment_card_id: int) -> dict[str, Any]:
    """
    Delete payment card information.

    Args:
        payment_card_id: ID of the payment card to be deleted.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "payment_card_id": payment_card_id,
    }

    response = bridge.call_api(
        "amazon", "delete_payment_card", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_addresses() -> list[dict[str, Any]]:
    """
    Get a list of your addresses.

    Returns:
        Success: [{"address_id": int, "name": str, "street_address": str, "city": str, "state": str, "country": str, "zip_code": float}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }

    response = bridge.call_api("amazon", "show_addresses", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_add_address(
    name: str, street_address: str, city: str, state: str, country: str, zip_code: int
) -> dict[str, Any]:
    """
    Add a new address.

    Args:
        name: Name of the address, for example 'Home' or 'Work'. Minimum length: 1.
        street_address: Street address line. Minimum length: 1.
        city: Name of the city. Minimum length: 1.
        state: Name of the state. Minimum length: 1.
        country: Name of the country. Minimum length: 1.
        zip_code: 5-digit zip code of the address. Must be >= 10000 and < 100000.

    Returns:
        Success: {"message": str, "address_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "name": name,
        "street_address": street_address,
        "city": city,
        "state": state,
        "country": country,
        "zip_code": zip_code,
    }

    response = bridge.call_api("amazon", "add_address", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_address(
    address_id: int,
    name: str | None = None,
    street_address: str | None = None,
    city: str | None = None,
    state: str | None = None,
    country: str | None = None,
    zip_code: int | None = None,
) -> dict[str, Any]:
    """
    Update address information.

    Args:
        address_id: ID of the address to update
        name: New name for the address. Minimum length: 1. (optional)
        street_address: New street address line. Minimum length: 1. (optional)
        city: New city name for the address. Minimum length: 1. (optional)
        state: New state name for the address. Minimum length: 1. (optional)
        country: New country name for the address. Minimum length: 1. (optional)
        zip_code: New ZIP code for the address. Must be between 10000 and 99999. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "address_id": address_id,
    }
    if name is not None:
        params["name"] = name
    if street_address is not None:
        params["street_address"] = street_address
    if city is not None:
        params["city"] = city
    if state is not None:
        params["state"] = state
    if country is not None:
        params["country"] = country
    if zip_code is not None:
        params["zip_code"] = zip_code

    response = bridge.call_api("amazon", "update_address", method="patch", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_delete_address(address_id: int) -> dict[str, Any]:
    """
    Delete address information.

    Args:
        address_id: ID of the address to be deleted.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "address_id": address_id,
    }

    response = bridge.call_api("amazon", "delete_address", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_show_product_reviews(
    product_id: int,
    query: str | None = "",
    user_email: str | None = None,
    min_rating: int | None = 1,
    max_rating: int | None = 5,
    is_verified: bool | None = None,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Search or show a list of product reviews.

    Args:
        product_id: ID of the product to show reviews for.
        query: The search query string. (optional)
        user_email: Email of the user to filter reviews by. Must be a valid email address. (optional)
        min_rating: The minimum rating for a review. Must be between 1 and 5. (optional)
        max_rating: The maximum rating for a review. Must be between 1 and 5. (optional)
        is_verified: Filter reviews by whether they from a verified purchaser or not. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the product reviews by prefixed with +/- to reflect ascending/descending. Valid attributes: rating and created_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. (optional)

    Returns:
        Success: [{"review_id": int, "product_id": int, "is_verified": bool, "rating": float, "title": str, "text": str, "created_at": str (datetime), "user": dict}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "product_id": product_id,
    }
    if query is not None:
        params["query"] = query
    if user_email is not None:
        params["user_email"] = user_email
    if min_rating is not None:
        params["min_rating"] = min_rating
    if max_rating is not None:
        params["max_rating"] = max_rating
    if is_verified is not None:
        params["is_verified"] = is_verified
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("amazon", "show_product_reviews", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_write_product_review(
    product_id: int, rating: int, title: str | None = "", text: str | None = ""
) -> dict[str, Any]:
    """
    Write a product review.

    Args:
        product_id: ID of the product to review.
        rating: Product rating for this review. Must be between 1 and 5.
        title: Title of the review. (optional)
        text: Text content of the review. (optional)

    Returns:
        Success: {"message": str, "product_review_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
        "rating": rating,
    }
    if title is not None:
        params["title"] = title
    if text is not None:
        params["text"] = text

    response = bridge.call_api(
        "amazon", "write_product_review", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_product_review(
    review_id: int,
    rating: int | None = None,
    title: str | None = None,
    text: str | None = None,
) -> dict[str, Any]:
    """
    Update a product review.

    Args:
        review_id: ID of the product review.
        rating: Product rating for this review. Must be between 1 and 5. (optional)
        title: Title of the review. (optional)
        text: Text content of the review. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "review_id": review_id,
    }
    if rating is not None:
        params["rating"] = rating
    if title is not None:
        params["title"] = title
    if text is not None:
        params["text"] = text

    response = bridge.call_api(
        "amazon", "update_product_review", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_delete_product_review(review_id: int) -> dict[str, Any]:
    """
    Delete a product review.

    Args:
        review_id: ID of the product review.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "review_id": review_id,
    }

    response = bridge.call_api(
        "amazon", "delete_product_review", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_show_product_questions(
    product_id: int,
    query: str | None = "",
    user_email: str | None = None,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Search or show a list of product questions.

    Args:
        product_id: ID of the product to show questions for.
        query: The search query string. (optional)
        user_email: Email of the user who posted the question. Must be a valid email address. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the questions by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. (optional)

    Returns:
        Success: [{"product_id": int, "question_id": int, "question": str, "num_answers": int, "created_at": str (datetime), "user": dict}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "product_id": product_id,
    }
    if query is not None:
        params["query"] = query
    if user_email is not None:
        params["user_email"] = user_email
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api(
        "amazon", "show_product_questions", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_write_product_question(product_id: int, question: str) -> dict[str, Any]:
    """
    Post a question about a product.

    Args:
        product_id: ID of the product to ask a question about.
        question: Question to be written for the product. Minimum length: 1.

    Returns:
        Success: {"message": str, "question_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "product_id": product_id,
        "question": question,
    }

    response = bridge.call_api(
        "amazon", "write_product_question", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_show_product_question_answers(
    question_id: int,
    query: str | None = "",
    user_email: str | None = None,
    is_verified: bool | None = None,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Search or show a list of answers to a product question.

    Args:
        question_id: ID of the product question.
        query: The search query string (optional)
        user_email: Email of the user who posted the answer. Must be a valid email address. (optional)
        is_verified: Filter answers by whether they from a verified purchaser or not. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the question answers by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. (optional)

    Returns:
        Success: [{"question_answer_id": int, "question_id": int, "is_verified": bool, "answer": str, "created_at": str (datetime), "user": dict}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "question_id": question_id,
    }
    if query is not None:
        params["query"] = query
    if user_email is not None:
        params["user_email"] = user_email
    if is_verified is not None:
        params["is_verified"] = is_verified
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api(
        "amazon", "show_product_question_answers", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_write_product_question_answer(
    question_id: int, answer: str
) -> dict[str, Any]:
    """
    Write an answer to a product question.

    Args:
        question_id: ID of the product question this is an answer to.
        answer: Answer to the question. Minimum length: 1.

    Returns:
        Success: {"message": str, "question_answer_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "question_id": question_id,
        "answer": answer,
    }

    response = bridge.call_api(
        "amazon", "write_product_question_answer", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_product_question(
    question_id: int, question: str | None = None
) -> dict[str, Any]:
    """
    Update a product question.

    Args:
        question_id: ID of the product question to update.
        question: The updated question. Minimum length: 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "question_id": question_id,
    }
    if question is not None:
        params["question"] = question

    response = bridge.call_api(
        "amazon", "update_product_question", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_delete_product_question(question_id: int) -> dict[str, Any]:
    """
    Delete a product question.

    Args:
        question_id: ID of the question to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "question_id": question_id,
    }

    response = bridge.call_api(
        "amazon", "delete_product_question", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_update_product_question_answer(
    question_answer_id: int, answer: str | None = None
) -> dict[str, Any]:
    """
    Update answer to a product question.

    Args:
        question_answer_id: ID of the question answer to update.
        answer: The updated answer for the question. Minimum length: 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "question_answer_id": question_answer_id,
    }
    if answer is not None:
        params["answer"] = answer

    response = bridge.call_api(
        "amazon", "update_product_question_answer", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_delete_product_question_answer(question_answer_id: int) -> dict[str, Any]:
    """
    Delete an answer to a product question.

    Args:
        question_answer_id: ID of the question answer to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "question_answer_id": question_answer_id,
    }

    response = bridge.call_api(
        "amazon", "delete_product_question_answer", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_returns(
    order_id: int | None = None,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = "-initiated_at",
) -> list[dict[str, Any]]:
    """
    Get a list of your product returns.

    Args:
        order_id: ID of the order to filter returns by. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the product returns by prefixed with +/- to reflect ascending/descending. Valid attributes: quantity, initiated_at and returned_at. (optional)

    Returns:
        Success: [{"return_id": int, "order_id": int, "product_id": int, "product_name": str, "quantity": float, "deliverer_id": int, "deliverer_name": str, "refund_amount": float, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }
    if order_id is not None:
        params["order_id"] = order_id
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("amazon", "show_returns", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_initiate_return(
    order_id: int, product_id: int, deliverer_id: int, quantity: int
) -> dict[str, Any]:
    """
    Initiate a product return.

    Args:
        order_id: ID of the order to be returned.
        product_id: ID of the product to be returned.
        deliverer_id: ID of the deliverer assigned to the return.
        quantity: Quantity of the product to be returned. Must be >= 1.

    Returns:
        Success: {"message": str, "return_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "order_id": order_id,
        "product_id": product_id,
        "deliverer_id": deliverer_id,
        "quantity": quantity,
    }

    response = bridge.call_api("amazon", "initiate_return", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_return(return_id: int) -> dict[str, Any]:
    """
    Show product return status.

    Args:
        return_id: ID of the product return.

    Returns:
        Success: {"return_id": int, "order_id": int, "product_id": int, "product_name": str, "quantity": float, "deliverer_id": int, "deliverer_name": str, "refund_amount": float, ...}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "return_id": return_id,
    }

    response = bridge.call_api("amazon", "show_return", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
def amazon_show_return_deliverers() -> list[dict[str, Any]]:
    """
    Get a list of product return deliverers.

    Returns:
        Success: [{"deliverer_id": int, "name": str}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}

    response = bridge.call_api(
        "amazon", "show_return_deliverers", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
def amazon_show_prime_plans() -> dict[str, Any]:
    """
    Show information about prime plans available. Delivery fee is waived for prime members.

    Returns:
        Success: {"monthly": int, "yearly": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}

    response = bridge.call_api("amazon", "show_prime_plans", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_subscribe_prime(payment_card_id: int, duration: str) -> dict[str, Any]:
    """
    Subscribe to prime membership.

    Args:
        payment_card_id: ID of the payment card to use for buy prime subscription.
        duration: Duration of the prime subscription. Must be one of: 'monthly', 'yearly'.

    Returns:
        Success: {"message": str, "prime_subscription_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "payment_card_id": payment_card_id,
        "duration": duration,
    }

    response = bridge.call_api("amazon", "subscribe_prime", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_show_prime_subscriptions(
    page_index: int | None = 0, page_limit: int | None = 5
) -> list[dict[str, Any]]:
    """
    Show your prime subscription history.

    Args:
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"prime_subscription_id": int, "start_date": str (datetime), "end_date": str (datetime), "payment_card_digits": str, "paid_amount": float}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
    }
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api(
        "amazon", "show_prime_subscriptions", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("amazon")
@requires_network
@requires_auth("amazon")
def amazon_download_prime_subscription_receipt(
    prime_subscription_id: int,
    file_system_access_token: str,
    download_to_file_path: str | None = None,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Download the receipt for a prime subscription.

    Args:
        prime_subscription_id: ID of the prime subscription to download the receipt for.
        file_system_access_token: Access token obtained from file_system app login.
        download_to_file_path: The file path to download the receipt file to in file system app. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. If not passed, it will be saved in your ~/downloads directory. (optional)
        overwrite: Whether to overwrite the file if it already exists. (optional)

    Returns:
        Success: {"message": str, "file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("amazon"),
        "prime_subscription_id": prime_subscription_id,
        "file_system_access_token": file_system_access_token,
    }
    if download_to_file_path is not None:
        params["download_to_file_path"] = download_to_file_path
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api(
        "amazon", "download_prime_subscription_receipt", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}
