"""
File System API tools for MMToolSandbox.

This module wraps AppWorld's File System APIs as MMToolSandbox-compatible tools
with state dependency checks (network, authentication).

Auto-generated by generate_static_wrappers.py
"""

from typing import Any

from mmtoolsandbox.appworld.bridge import get_appworld_bridge
from mmtoolsandbox.appworld.state import (
    get_appworld_state,
    requires_auth,
    requires_network,
)
from mmtoolsandbox.tools.appworld import register_appworld_tool


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_show_account() -> dict[str, Any]:
    """
    Show your account information. Unlike show_profile, this includes private information.

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime), "last_logged_in": str (datetime), "verified": bool}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
    }

    response = bridge.call_api("file_system", "show_account", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
def file_system_signup(
    first_name: str, last_name: str, email: str, password: str
) -> dict[str, Any]:
    """
    Sign up to create account.

    Args:
        first_name: Your first name. Minimum length: 1.
        last_name: Your last name. Minimum length: 1.
        email: Your email address. Must be a valid email address.
        password: Your password. Minimum length: 5.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "first_name": first_name,
        "last_name": last_name,
        "email": email,
        "password": password,
    }

    response = bridge.call_api("file_system", "signup", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_delete_account() -> dict[str, Any]:
    """
    Delete your account.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
    }

    response = bridge.call_api(
        "file_system", "delete_account", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_update_account_name(
    first_name: str | None = None, last_name: str | None = None
) -> dict[str, Any]:
    """
    Update your first or last name in the account profile.

    Args:
        first_name: Your updated first name. Minimum length: 1. (optional)
        last_name: Your updated last name. Minimum length: 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
    }
    if first_name is not None:
        params["first_name"] = first_name
    if last_name is not None:
        params["last_name"] = last_name

    response = bridge.call_api(
        "file_system", "update_account_name", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
def file_system_login(username: str, password: str) -> dict[str, Any]:
    """
    Login to your account.

    Args:
        username: Your account email.
        password: Your account password.

    Returns:
        Success: {"access_token": str, "token_type": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "username": username,
        "password": password,
    }

    response = bridge.call_api("file_system", "login", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Register login state
    if isinstance(response, dict) and "access_token" in response:
        appworld_state.login(
            "file_system", response["access_token"], response.get("user_id")
        )

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_logout() -> dict[str, Any]:
    """
    Logout from your account.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
    }

    response = bridge.call_api("file_system", "logout", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
def file_system_send_verification_code(email: str) -> dict[str, Any]:
    """
    Send account verification code to your email address.

    Args:
        email: Your email address. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
    }

    response = bridge.call_api(
        "file_system", "send_verification_code", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
def file_system_verify_account(email: str, verification_code: str) -> dict[str, Any]:
    """
    Verify your account using the verification code sent to your email address.

    Args:
        email: Your email address. Must be a valid email address.
        verification_code: The verification code sent to your email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
        "verification_code": verification_code,
    }

    response = bridge.call_api("file_system", "verify_account", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
def file_system_send_password_reset_code(email: str) -> dict[str, Any]:
    """
    Send password reset code to your email address.

    Args:
        email: Your email address. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
    }

    response = bridge.call_api(
        "file_system", "send_password_reset_code", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
def file_system_reset_password(
    email: str, password_reset_code: str, new_password: str
) -> dict[str, Any]:
    """
    Reset your password using the password reset code sent to your email address.

    Args:
        email: Your email address. Must be a valid email address.
        password_reset_code: The password reset code sent to your email address.
        new_password: Your new password. Minimum length: 5.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
        "password_reset_code": password_reset_code,
        "new_password": new_password,
    }

    response = bridge.call_api("file_system", "reset_password", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
def file_system_show_profile(email: str | None = None) -> dict[str, Any]:
    """
    Show public profile information of a user.

    Args:
        email: Email of the person you want to see the profile information of. Must be a valid email address. (optional)

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime)}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if email is not None:
        params["email"] = email

    response = bridge.call_api("file_system", "show_profile", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_create_directory(
    directory_path: str,
    recursive: bool | None = False,
    allow_if_exists: bool | None = True,
) -> dict[str, Any]:
    """
    Create a directory if it does not exist, optionally recursively.

    Args:
        directory_path: Path of the directory. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        recursive: If True, it will create all parent directories recursively if they don't exist. (optional)
        allow_if_exists: If True, it will not raise an error if the directory already exists. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "directory_path": directory_path,
    }
    if recursive is not None:
        params["recursive"] = recursive
    if allow_if_exists is not None:
        params["allow_if_exists"] = allow_if_exists

    response = bridge.call_api(
        "file_system", "create_directory", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_delete_directory(directory_path: str) -> dict[str, Any]:
    """
    Delete a directory with its sub-directories and files.

    Args:
        directory_path: Path of the directory. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "directory_path": directory_path,
    }

    response = bridge.call_api(
        "file_system", "delete_directory", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_show_directory(
    directory_path: str | None = "/",
    substring: str | None = None,
    entry_type: str | None = "all",
    recursive: bool | None = True,
) -> list[dict[str, Any]]:
    """
    Show a list of files and/or sub-directories, optionally recursively, in a directory.

    Args:
        directory_path: Path of the directory. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. Minimum length: 1. (optional)
        substring: If passed, only files and sub-directories containing the given substring (ignoring case) will be shown. (optional)
        entry_type: Whether to show all files and sub-directories, only files, or only sub-directories. Must be one of: 'all', 'files', 'directories'. (optional)
        recursive: Whether to show files recursively. (optional)

    Returns:
        Success: [str]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
    }
    if directory_path is not None:
        params["directory_path"] = directory_path
    if substring is not None:
        params["substring"] = substring
    if entry_type is not None:
        params["entry_type"] = entry_type
    if recursive is not None:
        params["recursive"] = recursive

    response = bridge.call_api("file_system", "show_directory", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_directory_exists(directory_path: str) -> dict[str, Any]:
    """
    Check if a directory exists.

    Args:
        directory_path: Path of the directory. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. Minimum length: 1.

    Returns:
        Success: {"exists": bool}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "directory_path": directory_path,
    }

    response = bridge.call_api(
        "file_system", "directory_exists", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_show_file(file_path: str) -> dict[str, Any]:
    """
    Show a file's content and other details, if it exists.

    Args:
        file_path: Path of the file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.

    Returns:
        Success: {"file_id": int, "path": str, "content": str, "created_at": str (datetime), "updated_at": str (datetime)}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "file_path": file_path,
    }

    response = bridge.call_api("file_system", "show_file", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_create_file(
    file_path: str, content: str | None = "", overwrite: bool | None = False
) -> dict[str, Any]:
    """
    Create a new file with the given content.

    Args:
        file_path: Path of the file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        content: The content of the file. (optional)
        overwrite: Whether to overwrite the file if it already exists. (optional)

    Returns:
        Success: {"message": str, "file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "file_path": file_path,
    }
    if content is not None:
        params["content"] = content
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api("file_system", "create_file", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_update_file(file_path: str, content: str) -> dict[str, Any]:
    """
    Update a file's content.

    Args:
        file_path: Path of the file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        content: The updated content of the file.

    Returns:
        Success: {"message": str, "file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "file_path": file_path,
        "content": content,
    }

    response = bridge.call_api("file_system", "update_file", method="patch", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_delete_file(file_path: str) -> dict[str, Any]:
    """
    Delete a file.

    Args:
        file_path: Path of the file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.

    Returns:
        Success: {"message": str, "file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "file_path": file_path,
    }

    response = bridge.call_api("file_system", "delete_file", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_file_exists(file_path: str) -> dict[str, Any]:
    """
    Check if a file exists.

    Args:
        file_path: Path of the file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. Minimum length: 1.

    Returns:
        Success: {"exists": bool}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "file_path": file_path,
    }

    response = bridge.call_api("file_system", "file_exists", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_copy_file(
    source_file_path: str,
    destination_file_path: str,
    overwrite: bool | None = False,
    retain_dates: bool | None = False,
) -> dict[str, Any]:
    """
    Copy a file to another location.

    Args:
        source_file_path: Path of the source file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        destination_file_path: Path of the destination file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        overwrite: Whether to overwrite the file if it already exists. (optional)
        retain_dates: Whether the copied file should retain the original file's created and updated dates. (optional)

    Returns:
        Success: {"message": str, "destination_file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "source_file_path": source_file_path,
        "destination_file_path": destination_file_path,
    }
    if overwrite is not None:
        params["overwrite"] = overwrite
    if retain_dates is not None:
        params["retain_dates"] = retain_dates

    response = bridge.call_api("file_system", "copy_file", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_move_file(
    source_file_path: str,
    destination_file_path: str,
    overwrite: bool | None = False,
    retain_dates: bool | None = False,
) -> dict[str, Any]:
    """
    Move a file to another location.

    Args:
        source_file_path: Path of the source file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        destination_file_path: Path of the destination file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        overwrite: Whether to overwrite the file if it already exists. (optional)
        retain_dates: Whether the moved file should retain the original file's created and updated dates. (optional)

    Returns:
        Success: {"message": str, "destination_file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "source_file_path": source_file_path,
        "destination_file_path": destination_file_path,
    }
    if overwrite is not None:
        params["overwrite"] = overwrite
    if retain_dates is not None:
        params["retain_dates"] = retain_dates

    response = bridge.call_api("file_system", "move_file", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_copy_directory(
    source_directory_path: str,
    destination_directory_path: str,
    overwrite: bool | None = False,
    retain_dates: bool | None = False,
) -> dict[str, Any]:
    """
    Copy a directory to another location.

    Args:
        source_directory_path: Path of the source directory. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        destination_directory_path: Path of the destination directory. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        overwrite: Whether to overwrite the directory if it already exists. (optional)
        retain_dates: Whether the files in the copied directory should retain the created and updated dates of the files in the original directory. (optional)

    Returns:
        Success: {"message": str, "destination_directory_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "source_directory_path": source_directory_path,
        "destination_directory_path": destination_directory_path,
    }
    if overwrite is not None:
        params["overwrite"] = overwrite
    if retain_dates is not None:
        params["retain_dates"] = retain_dates

    response = bridge.call_api("file_system", "copy_directory", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_move_directory(
    source_directory_path: str,
    destination_directory_path: str,
    overwrite: bool | None = False,
    retain_dates: bool | None = False,
) -> dict[str, Any]:
    """
    Move a directory to another location.

    Args:
        source_directory_path: Path of the source directory. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        destination_directory_path: Path of the destination directory. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        overwrite: Whether to overwrite the directory if it already exists. (optional)
        retain_dates: Whether the files in the moved directory should retain the created and updated dates of the files in the original directory. (optional)

    Returns:
        Success: {"message": str, "destination_directory_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "source_directory_path": source_directory_path,
        "destination_directory_path": destination_directory_path,
    }
    if overwrite is not None:
        params["overwrite"] = overwrite
    if retain_dates is not None:
        params["retain_dates"] = retain_dates

    response = bridge.call_api("file_system", "move_directory", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_compress_directory(
    directory_path: str,
    compressed_file_path: str | None = None,
    delete_directory: bool | None = False,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Compress a directory.

    Args:
        directory_path: Path of the directory to compress. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'.
        compressed_file_path: Path of the compressed file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. If passed, must have an extension: zip or tar. If not passed, it'll be stored as a zip file with the base name of directory_path in directory_path's parent directory. (optional)
        delete_directory: Whether to delete the directory after compression. (optional)
        overwrite: Whether to overwrite the compressed file if it already exists. (optional)

    Returns:
        Success: {"message": str, "compressed_file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "directory_path": directory_path,
    }
    if compressed_file_path is not None:
        params["compressed_file_path"] = compressed_file_path
    if delete_directory is not None:
        params["delete_directory"] = delete_directory
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api(
        "file_system", "compress_directory", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("file_system")
@requires_network
@requires_auth("file_system")
def file_system_decompress_file(
    compressed_file_path: str,
    decompressed_directory_path: str | None = None,
    overwrite: bool | None = False,
    retain_dates: bool | None = True,
    delete_compressed_file: bool | None = False,
) -> dict[str, Any]:
    """
    Decompress a compressed file.

    Args:
        compressed_file_path: Path of the compressed file. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. Must have an extension: zip or tar.
        decompressed_directory_path: Path of the directory to save decompressed files. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. If not passed, it'll be saved in the same directory as the compressed file. (optional)
        overwrite: Whether to overwrite the decompressed directory if it already exists. (optional)
        retain_dates: Whether the decompressed files should retain the created and updated dates of the files in the compressed file. (optional)
        delete_compressed_file: Whether to delete the compressed file after decompression. (optional)

    Returns:
        Success: {"message": str, "decompressed_directory_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("file_system"),
        "compressed_file_path": compressed_file_path,
    }
    if decompressed_directory_path is not None:
        params["decompressed_directory_path"] = decompressed_directory_path
    if overwrite is not None:
        params["overwrite"] = overwrite
    if retain_dates is not None:
        params["retain_dates"] = retain_dates
    if delete_compressed_file is not None:
        params["delete_compressed_file"] = delete_compressed_file

    response = bridge.call_api(
        "file_system", "decompress_file", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}
