"""
Gmail API tools for MMToolSandbox.

This module wraps AppWorld's Gmail APIs as MMToolSandbox-compatible tools
with state dependency checks (network, authentication).

Auto-generated by generate_static_wrappers.py
"""

from typing import Any

from mmtoolsandbox.appworld.bridge import get_appworld_bridge
from mmtoolsandbox.appworld.state import (
    get_appworld_state,
    requires_auth,
    requires_network,
)
from mmtoolsandbox.tools.appworld import register_appworld_tool


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_account() -> dict[str, Any]:
    """
    Show your account information. Unlike show_profile, this includes private information.

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime), "last_logged_in": str (datetime), "status": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }

    response = bridge.call_api("gmail", "show_account", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
def gmail_signup(
    first_name: str, last_name: str, email: str, password: str
) -> dict[str, Any]:
    """
    Sign up to create account.

    Args:
        first_name: Your first name. Minimum length: 1.
        last_name: Your last name. Minimum length: 1.
        email: Your email address. Must be a valid email address.
        password: Your password. Minimum length: 5.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "first_name": first_name,
        "last_name": last_name,
        "email": email,
        "password": password,
    }

    response = bridge.call_api("gmail", "signup", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_delete_account() -> dict[str, Any]:
    """
    Delete your account.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }

    response = bridge.call_api("gmail", "delete_account", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_update_account_name(
    first_name: str | None = None, last_name: str | None = None
) -> dict[str, Any]:
    """
    Update your first or last name in the account profile.

    Args:
        first_name: Your updated first name. Minimum length: 1. (optional)
        last_name: Your updated last name. Minimum length: 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if first_name is not None:
        params["first_name"] = first_name
    if last_name is not None:
        params["last_name"] = last_name

    response = bridge.call_api("gmail", "update_account_name", method="patch", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
def gmail_login(username: str, password: str) -> dict[str, Any]:
    """
    Login to your account.

    Args:
        username: Your account email.
        password: Your account password.

    Returns:
        Success: {"access_token": str, "token_type": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "username": username,
        "password": password,
    }

    response = bridge.call_api("gmail", "login", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Register login state
    if isinstance(response, dict) and "access_token" in response:
        appworld_state.login("gmail", response["access_token"], response.get("user_id"))

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_logout() -> dict[str, Any]:
    """
    Logout from your account.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }

    response = bridge.call_api("gmail", "logout", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
def gmail_send_password_reset_code(email: str) -> dict[str, Any]:
    """
    Send password reset code to your email address.

    Args:
        email: Your email address. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
    }

    response = bridge.call_api(
        "gmail", "send_password_reset_code", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
def gmail_reset_password(
    email: str, password_reset_code: str, new_password: str
) -> dict[str, Any]:
    """
    Reset your password using the password reset code sent to your email address.

    Args:
        email: Your email address. Must be a valid email address.
        password_reset_code: The password reset code sent to your email address.
        new_password: Your new password. Minimum length: 5.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
        "password_reset_code": password_reset_code,
        "new_password": new_password,
    }

    response = bridge.call_api("gmail", "reset_password", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
def gmail_show_profile(email: str | None = None) -> dict[str, Any]:
    """
    Show public profile information of a user.

    Args:
        email: Email of the person you want to see the profile information of. Must be a valid email address. (optional)

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime), "status": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if email is not None:
        params["email"] = email

    response = bridge.call_api("gmail", "show_profile", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_set_status(status: str, status_expiry: str | None = None) -> dict[str, Any]:
    """
    Set your availability status.

    Args:
        status: Your availability status. Must be one of: 'active', 'do_not_disturb', 'away'.
        status_expiry: When the status expires, in YYYY-MM-DD|HH:MM:SS format. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "status": status,
    }
    if status_expiry is not None:
        params["status_expiry"] = status_expiry

    response = bridge.call_api("gmail", "set_status", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
def gmail_search_users(
    query: str | None = "",
    page_index: int | None = 0,
    page_limit: int | None = 5,
) -> list[dict[str, Any]]:
    """
    Search Gmail users by name or email address.

    Args:
        query: Search query string. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime), "status": str}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if query is not None:
        params["query"] = query
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api("gmail", "search_users", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_search_labels(
    query: str | None = "",
    page_index: int | None = 0,
    page_limit: int | None = 5,
) -> list[dict[str, Any]]:
    """
    Search email thread labels by name.

    Args:
        query: Search query string. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be >= 1. (optional)

    Returns:
        Success: [str]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if query is not None:
        params["query"] = query
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api("gmail", "search_labels", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_inbox_threads(
    query: str | None = "",
    label: str | None = None,
    starred: bool | None = None,
    archived: bool | None = False,
    spam: bool | None = False,
    snoozed: bool | None = False,
    read: bool | None = None,
    attachment: bool | None = None,
    from_email: str | None = None,
    to_email: str | None = None,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search email threads you have received. This will not show detailed information about emails within the thread.

    Args:
        query: The search query string. (optional)
        label: The label to filter the emails by. (optional)
        starred: Filter emails by starred status. (optional)
        archived: Filter emails by archived status. (optional)
        spam: Filter emails by spam status. (optional)
        snoozed: Filter emails by snoozed status. (optional)
        read: Filter emails by read status. (optional)
        attachment: Filter emails by whether they have an attachment or not. (optional)
        from_email: Filter emails by sender email address. Must be a valid email address. (optional)
        to_email: Filter emails by recipient email address. Must be a valid email address. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the email threads by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and updated_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -updated_at. (optional)

    Returns:
        Success: [{"email_thread_id": int, "email_ids": list[int], "draft_ids": list[int], "incoming": bool, "outgoing": bool, "read": bool, "label": str, "snoozed_until": str (datetime), ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if query is not None:
        params["query"] = query
    if label is not None:
        params["label"] = label
    if starred is not None:
        params["starred"] = starred
    if archived is not None:
        params["archived"] = archived
    if spam is not None:
        params["spam"] = spam
    if snoozed is not None:
        params["snoozed"] = snoozed
    if read is not None:
        params["read"] = read
    if attachment is not None:
        params["attachment"] = attachment
    if from_email is not None:
        params["from_email"] = from_email
    if to_email is not None:
        params["to_email"] = to_email
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("gmail", "show_inbox_threads", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_outbox_threads(
    query: str | None = "",
    label: str | None = None,
    starred: bool | None = None,
    archived: bool | None = False,
    spam: bool | None = False,
    snoozed: bool | None = False,
    read: bool | None = None,
    attachment: bool | None = None,
    from_email: str | None = None,
    to_email: str | None = None,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search email threads you have sent. This will not show detailed information about emails within the thread.

    Args:
        query: The search query string. (optional)
        label: The label to filter the emails by. (optional)
        starred: Filter emails by starred status. (optional)
        archived: Filter emails by archived status. (optional)
        spam: Filter emails by spam status. (optional)
        snoozed: Filter emails by snoozed status. (optional)
        read: Filter emails by read status. (optional)
        attachment: Filter emails by attachment status. (optional)
        from_email: Filter emails by sender email address. Must be a valid email address. (optional)
        to_email: Filter emails by recipient email address. Must be a valid email address. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the email threads by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and updated_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -updated_at. (optional)

    Returns:
        Success: [{"email_thread_id": int, "email_ids": list[int], "draft_ids": list[int], "incoming": bool, "outgoing": bool, "read": bool, "label": str, "snoozed_until": str (datetime), ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if query is not None:
        params["query"] = query
    if label is not None:
        params["label"] = label
    if starred is not None:
        params["starred"] = starred
    if archived is not None:
        params["archived"] = archived
    if spam is not None:
        params["spam"] = spam
    if snoozed is not None:
        params["snoozed"] = snoozed
    if read is not None:
        params["read"] = read
    if attachment is not None:
        params["attachment"] = attachment
    if from_email is not None:
        params["from_email"] = from_email
    if to_email is not None:
        params["to_email"] = to_email
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("gmail", "show_outbox_threads", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_snoozed_threads(
    query: str | None = "",
    label: str | None = None,
    starred: bool | None = None,
    read: bool | None = None,
    attachment: bool | None = None,
    from_email: str | None = None,
    to_email: str | None = None,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search email threads you have snoozed. This will not show detailed information about emails within the thread.

    Args:
        query: The search query string. (optional)
        label: The label to filter the emails by. (optional)
        starred: Filter emails by starred status. (optional)
        read: Filter emails by read status. (optional)
        attachment: Filter emails by attachment status. (optional)
        from_email: Filter emails by sender email address. Must be a valid email address. (optional)
        to_email: Filter emails by recipient email address. Must be a valid email address. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the email threads by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and updated_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -updated_at. (optional)

    Returns:
        Success: [{"email_thread_id": int, "email_ids": list[int], "draft_ids": list[int], "incoming": bool, "outgoing": bool, "read": bool, "label": str, "snoozed_until": str (datetime), ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if query is not None:
        params["query"] = query
    if label is not None:
        params["label"] = label
    if starred is not None:
        params["starred"] = starred
    if read is not None:
        params["read"] = read
    if attachment is not None:
        params["attachment"] = attachment
    if from_email is not None:
        params["from_email"] = from_email
    if to_email is not None:
        params["to_email"] = to_email
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("gmail", "show_snoozed_threads", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_starred_threads(
    query: str | None = "",
    label: str | None = None,
    archived: bool | None = None,
    spam: bool | None = None,
    snoozed: bool | None = None,
    read: bool | None = None,
    attachment: bool | None = None,
    from_email: str | None = None,
    to_email: str | None = None,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search email threads you have starred. This will not show detailed information about emails within the thread.

    Args:
        query: The search query string. (optional)
        label: The label to filter the emails by. (optional)
        archived: Filter emails by archived status. (optional)
        spam: Filter emails by spam status. (optional)
        snoozed: Filter emails by snoozed status. (optional)
        read: Filter emails by read status. (optional)
        attachment: Filter emails by attachment status. (optional)
        from_email: Filter emails by sender email address. Must be a valid email address. (optional)
        to_email: Filter emails by recipient email address. Must be a valid email address. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the email threads by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and updated_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -updated_at. (optional)

    Returns:
        Success: [{"email_thread_id": int, "email_ids": list[int], "draft_ids": list[int], "incoming": bool, "outgoing": bool, "read": bool, "label": str, "snoozed_until": str (datetime), ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if query is not None:
        params["query"] = query
    if label is not None:
        params["label"] = label
    if archived is not None:
        params["archived"] = archived
    if spam is not None:
        params["spam"] = spam
    if snoozed is not None:
        params["snoozed"] = snoozed
    if read is not None:
        params["read"] = read
    if attachment is not None:
        params["attachment"] = attachment
    if from_email is not None:
        params["from_email"] = from_email
    if to_email is not None:
        params["to_email"] = to_email
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("gmail", "show_starred_threads", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_archived_threads(
    query: str | None = "",
    label: str | None = None,
    starred: bool | None = None,
    read: bool | None = None,
    attachment: bool | None = None,
    from_email: str | None = None,
    to_email: str | None = None,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search email threads you have archived. This will not show detailed information about emails within the thread.

    Args:
        query: The search query string. (optional)
        label: The label to filter the emails by. (optional)
        starred: Filter emails by starred status. (optional)
        read: Filter emails by read status. (optional)
        attachment: Filter emails by attachment status. (optional)
        from_email: Filter emails by sender email address. Must be a valid email address. (optional)
        to_email: Filter emails by recipient email address. Must be a valid email address. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the email threads by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and updated_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -updated_at. (optional)

    Returns:
        Success: [{"email_thread_id": int, "email_ids": list[int], "draft_ids": list[int], "incoming": bool, "outgoing": bool, "read": bool, "label": str, "snoozed_until": str (datetime), ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if query is not None:
        params["query"] = query
    if label is not None:
        params["label"] = label
    if starred is not None:
        params["starred"] = starred
    if read is not None:
        params["read"] = read
    if attachment is not None:
        params["attachment"] = attachment
    if from_email is not None:
        params["from_email"] = from_email
    if to_email is not None:
        params["to_email"] = to_email
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("gmail", "show_archived_threads", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_spam_threads(
    query: str | None = "",
    label: str | None = None,
    starred: bool | None = None,
    read: bool | None = None,
    attachment: bool | None = None,
    from_email: str | None = None,
    to_email: str | None = None,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search email threads that have been marked as spam. This will not show detailed information about emails within the thread.

    Args:
        query: The search query string. (optional)
        label: The label to filter the emails by. (optional)
        starred: Filter emails by starred status. (optional)
        read: Filter emails by read status. (optional)
        attachment: Filter emails by attachment status. (optional)
        from_email: Filter emails by sender email address. Must be a valid email address. (optional)
        to_email: Filter emails by recipient email address. Must be a valid email address. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the email threads by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and updated_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -updated_at. (optional)

    Returns:
        Success: [{"email_thread_id": int, "email_ids": list[int], "draft_ids": list[int], "incoming": bool, "outgoing": bool, "read": bool, "label": str, "snoozed_until": str (datetime), ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if query is not None:
        params["query"] = query
    if label is not None:
        params["label"] = label
    if starred is not None:
        params["starred"] = starred
    if read is not None:
        params["read"] = read
    if attachment is not None:
        params["attachment"] = attachment
    if from_email is not None:
        params["from_email"] = from_email
    if to_email is not None:
        params["to_email"] = to_email
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("gmail", "show_spam_threads", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_category_sizes(read: bool | None = None) -> dict[str, Any]:
    """
    Show the number of email threads in each category of inbox, outbox, archived, spam, and the number of unscheduled and scheduled email drafts.

    Args:
        read: Count only read or unread email threads. If None, count both read and unread threads. It is not applicable for drafts. (optional)

    Returns:
        Success: {"inbox": int, "outbox": int, "snoozed": int, "starred": int, "archived": int, "spam": int, "unscheduled_drafts": int, "scheduled_drafts": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if read is not None:
        params["read"] = read

    response = bridge.call_api("gmail", "show_category_sizes", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_thread(email_thread_id: int) -> dict[str, Any]:
    """
    Show detailed information about a given email thread, including emails and drafts within it.

    Args:
        email_thread_id: The ID of the email thread to show.

    Returns:
        Success: {"email_thread_id": int, "incoming": bool, "outgoing": bool, "read": bool, "label": str, "snoozed_until": str (datetime), "starred": bool, "archived": bool, ...}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "show_thread", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_delete_thread(email_thread_id: int) -> dict[str, Any]:
    """
    Delete an email thread.

    Args:
        email_thread_id: The ID of the email thread to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "delete_thread", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_email(email_id: int) -> dict[str, Any]:
    """
    Show detailed information about a given email.

    Args:
        email_id: The ID of the email to show.

    Returns:
        Success: {"email_id": int, "subject": str, "body": str, "response_to_email_id": int, "created_at": str (datetime), "sender": dict, "recipients": list[dict], "attachments": list[dict]}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_id": email_id,
    }

    response = bridge.call_api("gmail", "show_email", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_label_thread(email_thread_id: int, label: str) -> dict[str, Any]:
    """
    Label an email thread.

    Args:
        email_thread_id: The ID of the email thread to label.
        label: The label to assign to the email thread.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
        "label": label,
    }

    response = bridge.call_api("gmail", "label_thread", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_unlabel_thread(email_thread_id: int) -> dict[str, Any]:
    """
    Remove label from an email thread.

    Args:
        email_thread_id: The ID of the email thread to unlabel.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "unlabel_thread", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_mark_thread_read(email_thread_id: int) -> dict[str, Any]:
    """
    Mark an email thread as read.

    Args:
        email_thread_id: The ID of the email thread to mark as read.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "mark_thread_read", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_mark_thread_unread(email_thread_id: int) -> dict[str, Any]:
    """
    Mark an email thread as unread.

    Args:
        email_thread_id: The ID of the email thread to mark as unread.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "mark_thread_unread", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_mark_thread_archived(email_thread_id: int) -> dict[str, Any]:
    """
    Mark an email thread as archived. This will also remove the spam and snooze status if any.

    Args:
        email_thread_id: The ID of the email thread to archive.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "mark_thread_archived", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_mark_thread_unarchived(email_thread_id: int) -> dict[str, Any]:
    """
    Mark an email thread as unarchived.

    Args:
        email_thread_id: The ID of the email thread to unarchive.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api(
        "gmail", "mark_thread_unarchived", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_mark_thread_spam(email_thread_id: int) -> dict[str, Any]:
    """
    Mark an email thread as spam. This will also remove the archived and snooze status if any.

    Args:
        email_thread_id: The ID of the email thread to mark as spam.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "mark_thread_spam", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_mark_thread_not_spam(email_thread_id: int) -> dict[str, Any]:
    """
    Mark an email thread as not spam.

    Args:
        email_thread_id: The ID of the email thread to mark as not spam.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "mark_thread_not_spam", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_mark_thread_starred(email_thread_id: int) -> dict[str, Any]:
    """
    Mark an email thread as starred.

    Args:
        email_thread_id: The ID of the email thread to star.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "mark_thread_starred", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_mark_thread_unstarred(email_thread_id: int) -> dict[str, Any]:
    """
    Mark an email thread as unstarred.

    Args:
        email_thread_id: The ID of the email thread to unstar.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api(
        "gmail", "mark_thread_unstarred", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_delete_email_in_thread(email_thread_id: int, email_id: int) -> dict[str, Any]:
    """
    Delete an email in a thread.

    Args:
        email_thread_id: The ID of the email thread to delete an email from.
        email_id: The ID of the email to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
        "email_id": email_id,
    }

    response = bridge.call_api(
        "gmail", "delete_email_in_thread", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_snooze_thread(email_thread_id: int, snooze_until: str) -> dict[str, Any]:
    """
    Snooze an email thread until a given date and time in the future. It will reappear in unread state in your inbox and/or outbox at that time. It will also be removed from archived or spam categories if it was in either of those.

    Args:
        email_thread_id: The ID of the email thread to snooze.
        snooze_until: The date and time to snooze the email thread until. The date and time should be in YYYY-MM-DD|HH:MM:SS format

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
        "snooze_until": snooze_until,
    }

    response = bridge.call_api("gmail", "snooze_thread", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_unsnooze_thread(email_thread_id: int) -> dict[str, Any]:
    """
    Unsnooze an email thread.

    Args:
        email_thread_id: The ID of the email thread to unsnooze.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
    }

    response = bridge.call_api("gmail", "unsnooze_thread", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_send_email(
    email_addresses: list[str],
    subject: str,
    body: str,
    attachment_file_paths: list[str] | None = None,
    file_system_access_token: str | None = None,
) -> dict[str, Any]:
    """
    Send a new email to one or more recipients.

    Args:
        email_addresses: List of recipient email addresses.
        subject: The subject of the email.
        body: The body of the email.
        attachment_file_paths: List of absolute file paths (starting with /) from the file_system app to attach to the email. (optional)
        file_system_access_token: Access token obtained from file_system app login. Only needed for attachments. (optional)

    Returns:
        Success: {"message": str, "sent_email_thread_id": int, "sent_email_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_addresses": email_addresses,
        "subject": subject,
        "body": body,
    }
    if attachment_file_paths is not None:
        params["attachment_file_paths"] = attachment_file_paths
    if file_system_access_token is not None:
        params["file_system_access_token"] = file_system_access_token

    response = bridge.call_api("gmail", "send_email", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_reply_to_email(
    email_thread_id: int,
    email_id: int,
    body: str,
    email_addresses: list[str] | None = None,
    attachment_file_paths: list[str] | None = None,
    file_system_access_token: str | None = None,
) -> dict[str, Any]:
    """
    Reply to an existing email in a thread.

    Args:
        email_thread_id: The ID of the email thread to reply to.
        email_id: The ID of the email to reply to.
        body: The body of the reply email.
        email_addresses: List of recipient email addresses. If passed, it'll reply to all recipients in the list, otherwise, to the sender. (optional)
        attachment_file_paths: List of absolute file paths (starting with /) from the file_system app to attach to the email. (optional)
        file_system_access_token: Access token obtained from file_system app login. Only needed for attachments. (optional)

    Returns:
        Success: {"message": str, "sent_email_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
        "email_id": email_id,
        "body": body,
    }
    if email_addresses is not None:
        params["email_addresses"] = email_addresses
    if attachment_file_paths is not None:
        params["attachment_file_paths"] = attachment_file_paths
    if file_system_access_token is not None:
        params["file_system_access_token"] = file_system_access_token

    response = bridge.call_api("gmail", "reply_to_email", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_forward_email_from_thread(
    email_thread_id: int,
    email_id: int,
    email_addresses: list[str],
    draft_not_send: bool | None = False,
) -> dict[str, Any]:
    """
    Forward an email from an email thread to one or more recipients.

    Args:
        email_thread_id: The ID of the email thread to forward.
        email_id: The ID of the email to forward.
        email_addresses: List of recipient email addresses.
        draft_not_send: If true, the email will be saved as a draft instead of being sent. This way it can be edited before sending. (optional)

    Returns:
        Success: {"message": str, "sent_email_thread_id": int, "sent_email_id": int, "draft_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
        "email_id": email_id,
        "email_addresses": email_addresses,
    }
    if draft_not_send is not None:
        params["draft_not_send"] = draft_not_send

    response = bridge.call_api(
        "gmail", "forward_email_from_thread", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_forward_email_thread(
    email_thread_id: int,
    email_addresses: list[str],
    draft_not_send: bool | None = False,
) -> dict[str, Any]:
    """
    Forward entire email thread to one or more recipients.

    Args:
        email_thread_id: The ID of the email thread to forward.
        email_addresses: List of recipient email addresses.
        draft_not_send: If true, the email will be saved as a draft instead of being sent. This way it can be edited before sending. (optional)

    Returns:
        Success: {"message": str, "sent_email_thread_id": int, "sent_email_id": int, "draft_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "email_thread_id": email_thread_id,
        "email_addresses": email_addresses,
    }
    if draft_not_send is not None:
        params["draft_not_send"] = draft_not_send

    response = bridge.call_api("gmail", "forward_email_thread", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_create_draft(
    recipient_email_addresses: list[str],
    body: str,
    subject: str | None = None,
    belongs_to_email_thread_id: int | None = None,
    response_to_email_id: int | None = None,
    attachment_file_paths: list[str] | None = None,
    scheduled_send_at: str | None = None,
    file_system_access_token: str | None = None,
) -> dict[str, Any]:
    """
    Create a new draft.

    Args:
        recipient_email_addresses: List of recipient email addresses.
        body: The body of the draft.
        subject: The subject of the draft. Must be None if it's a reply to an email. (optional)
        belongs_to_email_thread_id: The ID of the email thread that the draft should belong to. Must be passed if it's a reply to or forward of an email. (optional)
        response_to_email_id: The ID of the email in the thread that the draft should responds to. (optional)
        attachment_file_paths: List of absolute file paths (starting with /) from the file_system app to attach to the draft. (optional)
        scheduled_send_at: If set, the draft will be sent at the specified future time in YYYY-MM-DD|HH:MM:SS format. Otherwise, it will not be sent until you manually send it. (optional)
        file_system_access_token: Access token obtained from file_system app login. Only needed for attachments. (optional)

    Returns:
        Success: {"message": str, "draft_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "recipient_email_addresses": recipient_email_addresses,
        "body": body,
    }
    if subject is not None:
        params["subject"] = subject
    if belongs_to_email_thread_id is not None:
        params["belongs_to_email_thread_id"] = belongs_to_email_thread_id
    if response_to_email_id is not None:
        params["response_to_email_id"] = response_to_email_id
    if attachment_file_paths is not None:
        params["attachment_file_paths"] = attachment_file_paths
    if scheduled_send_at is not None:
        params["scheduled_send_at"] = scheduled_send_at
    if file_system_access_token is not None:
        params["file_system_access_token"] = file_system_access_token

    response = bridge.call_api("gmail", "create_draft", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_drafts(
    query: str | None = "",
    recipient_email: str | None = None,
    attachment: bool | None = None,
    scheduled: bool | None = None,
    belongs_to_email_thread_id: int | None = None,
    response_to_email_id: int | None = None,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Search or show a list of your drafts.

    Args:
        query: The search query string. (optional)
        recipient_email: Filter emails by recipient email address. Must be a valid email address. (optional)
        attachment: Filter drafts by attachment status. (optional)
        scheduled: Filter drafts by whether they are scheduled to be sent in the future. (optional)
        belongs_to_email_thread_id: Filter drafts by email thread ID that the draft belongs to. (optional)
        response_to_email_id: Filter drafts by email ID that the draft responds to. (optional)
        min_created_at: Filter drafts by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter drafts by maximum created_at date in YYYY-MM-DD format. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the drafts by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and updated_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -updated_at. (optional)

    Returns:
        Success: [{"draft_id": int, "subject": str, "body": str, "belongs_to_email_thread_id": int, "response_to_email_id": int, "scheduled_send_at": str (datetime), "created_at": str (datetime), "updated_at": str (datetime), ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
    }
    if query is not None:
        params["query"] = query
    if recipient_email is not None:
        params["recipient_email"] = recipient_email
    if attachment is not None:
        params["attachment"] = attachment
    if scheduled is not None:
        params["scheduled"] = scheduled
    if belongs_to_email_thread_id is not None:
        params["belongs_to_email_thread_id"] = belongs_to_email_thread_id
    if response_to_email_id is not None:
        params["response_to_email_id"] = response_to_email_id
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("gmail", "show_drafts", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_update_draft(
    draft_id: int,
    email_addresses: list[str] | None = None,
    subject: str | None = None,
    body: str | None = None,
    belongs_to_email_thread_id: int | None = None,
    response_to_email_id: int | None = None,
    scheduled_send_at: str | None = None,
) -> dict[str, Any]:
    """
    Update draft information.

    Args:
        draft_id: The ID of the draft to update.
        email_addresses: List of recipient email addresses. (optional)
        subject: The updated subject of the draft. (optional)
        body: The updated body of the draft. (optional)
        belongs_to_email_thread_id: The updated ID of the email thread that the draft should belong to. Must be passed if it's a reply to an email. (optional)
        response_to_email_id: The updated ID of the email in the thread that the draft is a response to. (optional)
        scheduled_send_at: The updated time at which the draft should be sent in YYYY-MM-DD|HH:MM:SS format.To remove the scheduled delivery, pass 'None' string, as leaving it empty or null is for when you don't want to update it. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "draft_id": draft_id,
    }
    if email_addresses is not None:
        params["email_addresses"] = email_addresses
    if subject is not None:
        params["subject"] = subject
    if body is not None:
        params["body"] = body
    if belongs_to_email_thread_id is not None:
        params["belongs_to_email_thread_id"] = belongs_to_email_thread_id
    if response_to_email_id is not None:
        params["response_to_email_id"] = response_to_email_id
    if scheduled_send_at is not None:
        params["scheduled_send_at"] = scheduled_send_at

    response = bridge.call_api("gmail", "update_draft", method="patch", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_delete_draft(draft_id: int) -> dict[str, Any]:
    """
    Delete draft information.

    Args:
        draft_id: The ID of the draft to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "draft_id": draft_id,
    }

    response = bridge.call_api("gmail", "delete_draft", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_show_draft(draft_id: int) -> dict[str, Any]:
    """
    Show detailed draft information.

    Args:
        draft_id: The ID of the draft to show.

    Returns:
        Success: {"draft_id": int, "subject": str, "body": str, "belongs_to_email_thread_id": int, "response_to_email_id": int, "scheduled_send_at": str (datetime), "created_at": str (datetime), "updated_at": str (datetime), ...}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "draft_id": draft_id,
    }

    response = bridge.call_api("gmail", "show_draft", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_send_email_from_draft(
    draft_id: int, file_system_access_token: str | None = None
) -> dict[str, Any]:
    """
    Send a new email from a draft right away.

    Args:
        draft_id: The ID of the draft to send.
        file_system_access_token: Access token obtained from file_system app login. Only needed if draft has attachments. (optional)

    Returns:
        Success: {"message": str, "sent_email_thread_id": int, "sent_email_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "draft_id": draft_id,
    }
    if file_system_access_token is not None:
        params["file_system_access_token"] = file_system_access_token

    response = bridge.call_api(
        "gmail", "send_email_from_draft", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_download_attachment(
    attachment_id: int,
    file_system_access_token: str,
    download_to_file_path: str | None = None,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Download a file attachment.

    Args:
        attachment_id: The ID of the attachment to download.
        file_system_access_token: Access token obtained from file_system app login.
        download_to_file_path: The file path to download the attachment to in file system app. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. If not passed, it will be saved in your ~/downloads directory. (optional)
        overwrite: Whether to overwrite the file if it already exists. (optional)

    Returns:
        Success: {"message": str, "file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "attachment_id": attachment_id,
        "file_system_access_token": file_system_access_token,
    }
    if download_to_file_path is not None:
        params["download_to_file_path"] = download_to_file_path
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api("gmail", "download_attachment", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_upload_attachments_to_draft(
    draft_id: int,
    attachment_file_paths: list[str],
    file_system_access_token: str,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Upload attachments to a draft.

    Args:
        draft_id: The ID of the draft to upload the attachment to.
        attachment_file_paths: List of absolute file paths (starting with /) from the file_system app to attach to the email.
        file_system_access_token: Access token obtained from file_system app login.
        overwrite: Whether to overwrite the attachment if it already exists. (optional)

    Returns:
        Success: {"message": str, "attachments": list[dict]}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "draft_id": draft_id,
        "attachment_file_paths": attachment_file_paths,
        "file_system_access_token": file_system_access_token,
    }
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api(
        "gmail", "upload_attachments_to_draft", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("gmail")
@requires_network
@requires_auth("gmail")
def gmail_remove_attachment_from_draft(
    draft_id: int, attachment_id: int
) -> dict[str, Any]:
    """
    Delete an attachment from a draft.

    Args:
        draft_id: The ID of the draft to delete the attachment from.
        attachment_id: The ID of the attachment to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("gmail"),
        "draft_id": draft_id,
        "attachment_id": attachment_id,
    }

    response = bridge.call_api(
        "gmail", "remove_attachment_from_draft", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}
