"""
Splitwise API tools for MMToolSandbox.

This module wraps AppWorld's Splitwise APIs as MMToolSandbox-compatible tools
with state dependency checks (network, authentication).

Auto-generated by generate_static_wrappers.py
"""

from typing import Any

from mmtoolsandbox.appworld.bridge import get_appworld_bridge
from mmtoolsandbox.appworld.state import (
    get_appworld_state,
    requires_auth,
    requires_network,
)
from mmtoolsandbox.tools.appworld import register_appworld_tool


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_account() -> dict[str, Any]:
    """
    Show your account information. Unlike show_profile, this includes private information.

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime), "last_logged_in": str (datetime), "verified": bool}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }

    response = bridge.call_api("splitwise", "show_account", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
def splitwise_signup(
    first_name: str, last_name: str, email: str, password: str
) -> dict[str, Any]:
    """
    Sign up to create account.

    Args:
        first_name: Your first name. Minimum length: 1.
        last_name: Your last name. Minimum length: 1.
        email: Your email address. Must be a valid email address.
        password: Your password. Minimum length: 5.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "first_name": first_name,
        "last_name": last_name,
        "email": email,
        "password": password,
    }

    response = bridge.call_api("splitwise", "signup", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_account() -> dict[str, Any]:
    """
    Delete your account.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }

    response = bridge.call_api("splitwise", "delete_account", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_update_account_name(
    first_name: str | None = None, last_name: str | None = None
) -> dict[str, Any]:
    """
    Update your first or last name in the account profile.

    Args:
        first_name: Your updated first name. Minimum length: 1. (optional)
        last_name: Your updated last name. Minimum length: 1. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if first_name is not None:
        params["first_name"] = first_name
    if last_name is not None:
        params["last_name"] = last_name

    response = bridge.call_api(
        "splitwise", "update_account_name", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
def splitwise_login(username: str, password: str) -> dict[str, Any]:
    """
    Login to your account.

    Args:
        username: Your account email.
        password: Your account password.

    Returns:
        Success: {"access_token": str, "token_type": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "username": username,
        "password": password,
    }

    response = bridge.call_api("splitwise", "login", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Register login state
    if isinstance(response, dict) and "access_token" in response:
        appworld_state.login(
            "splitwise", response["access_token"], response.get("user_id")
        )

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_logout() -> dict[str, Any]:
    """
    Logout from your account.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }

    response = bridge.call_api("splitwise", "logout", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
def splitwise_send_verification_code(email: str) -> dict[str, Any]:
    """
    Send account verification code to your email address.

    Args:
        email: Your email address. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
    }

    response = bridge.call_api(
        "splitwise", "send_verification_code", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
def splitwise_verify_account(email: str, verification_code: str) -> dict[str, Any]:
    """
    Verify your account using the verification code sent to your email address.

    Args:
        email: Your email address. Must be a valid email address.
        verification_code: The verification code sent to your email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
        "verification_code": verification_code,
    }

    response = bridge.call_api("splitwise", "verify_account", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
def splitwise_send_password_reset_code(email: str) -> dict[str, Any]:
    """
    Send password reset code to your email address.

    Args:
        email: Your email address. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
    }

    response = bridge.call_api(
        "splitwise", "send_password_reset_code", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
def splitwise_reset_password(
    email: str, password_reset_code: str, new_password: str
) -> dict[str, Any]:
    """
    Reset your password using the password reset code sent to your email address.

    Args:
        email: Your email address. Must be a valid email address.
        password_reset_code: The password reset code sent to your email address.
        new_password: Your new password. Minimum length: 5.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "email": email,
        "password_reset_code": password_reset_code,
        "new_password": new_password,
    }

    response = bridge.call_api("splitwise", "reset_password", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
def splitwise_show_profile(email: str | None = None) -> dict[str, Any]:
    """
    Show public profile information of a user.

    Args:
        email: Email of the person you want to see the profile information of. Must be a valid email address. (optional)

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "registered_at": str (datetime)}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}
    if email is not None:
        params["email"] = email

    response = bridge.call_api("splitwise", "show_profile", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_search_users(
    query: str | None = "",
    include_self: bool | None = False,
    page_index: int | None = 0,
    page_limit: int | None = 5,
) -> list[dict[str, Any]]:
    """
    Search Splitwise users by name or email address.

    Args:
        query: Search query string. (optional)
        include_self: Whether to include the current user in the search results. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"name": str, "email": str, "direction": str, "amount": float}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if query is not None:
        params["query"] = query
    if include_self is not None:
        params["include_self"] = include_self
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api("splitwise", "search_users", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_activity(
    show_expenses: bool | None = True,
    show_payments: bool | None = True,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = "-created_at",
) -> list[dict[str, Any]]:
    """
    Show a history of your expenses and payments combined.

    Args:
        show_expenses: Whether to show expenses in the history. (optional)
        show_payments: Whether to show payments in the history. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the expenses/payments by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at. (optional)

    Returns:
        Success: [{"record_type": str, "record_id": int, "amount": float, "paid_by": dict, "owed_by": list[dict], "description": str, "group_id": int, "group_name": str, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if show_expenses is not None:
        params["show_expenses"] = show_expenses
    if show_payments is not None:
        params["show_payments"] = show_payments
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api("splitwise", "show_activity", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_create_group(
    name: str, member_emails: list[str], description: str | None = None
) -> dict[str, Any]:
    """
    Create a new group of friends or family to share expenses with.

    Args:
        name: The name of the group. Minimum length: 1.
        member_emails: Emails of the users to add to the group besides yourself.
        description: The description of the group. (optional)

    Returns:
        Success: {"message": str, "group_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "name": name,
        "member_emails": member_emails,
    }
    if description is not None:
        params["description"] = description

    response = bridge.call_api("splitwise", "create_group", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_groups(
    delete: bool | None = False,
    page_index: int | None = 0,
    page_limit: int | None = 5,
) -> list[dict[str, Any]]:
    """
    Get a list of groups you are a member of.

    Args:
        delete: Filter groups by whether they are deleted or not. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be >= 1. (optional)

    Returns:
        Success: [{"group_id": int, "name": str, "description": str, "created_at": str (datetime), "deleted": bool, "creator": dict, "members": list[dict], "invitation_code": str}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if delete is not None:
        params["delete"] = delete
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api("splitwise", "show_groups", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_group(group_id: int) -> dict[str, Any]:
    """
    Show group details based on its ID.

    Args:
        group_id: The ID of the group.

    Returns:
        Success: {"group_id": int, "name": str, "description": str, "created_at": str (datetime), "deleted": bool, "creator": dict, "members": list[dict], "invitation_code": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
    }

    response = bridge.call_api("splitwise", "show_group", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_update_group(
    group_id: int, name: str | None = None, description: str | None = None
) -> dict[str, Any]:
    """
    Update group information.

    Args:
        group_id: The ID of the group.
        name: The updated name of the group. Minimum length: 1. (optional)
        description: The updated description of the group. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
    }
    if name is not None:
        params["name"] = name
    if description is not None:
        params["description"] = description

    response = bridge.call_api("splitwise", "update_group", method="patch", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_group(group_id: int) -> dict[str, Any]:
    """
    Delete a group you are a member of. Any member can undelete it later.

    Args:
        group_id: The ID of the group to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
    }

    response = bridge.call_api("splitwise", "delete_group", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_undelete_group(group_id: int) -> dict[str, Any]:
    """
    Undelete a group you are a member of.

    Args:
        group_id: The ID of the group to undelete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
    }

    response = bridge.call_api("splitwise", "undelete_group", method="patch", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_add_member_to_group(group_id: int, user_email: str) -> dict[str, Any]:
    """
    Add a member to a group.

    Args:
        group_id: The ID of the group.
        user_email: Email of the user to add to the group. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
        "user_email": user_email,
    }

    response = bridge.call_api(
        "splitwise", "add_member_to_group", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_remove_member_from_group(
    group_id: int, user_email: str
) -> dict[str, Any]:
    """
    Remove a member from a group.

    Args:
        group_id: The ID of the group.
        user_email: Email of the user to remove from the group. Must be a valid email address.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
        "user_email": user_email,
    }

    response = bridge.call_api(
        "splitwise", "remove_member_from_group", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_exit_group(group_id: int) -> dict[str, Any]:
    """
    Exit from a group you are a part of.

    Args:
        group_id: The ID of the group to exit.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
    }

    response = bridge.call_api("splitwise", "exit_group", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_regenerate_invitation_code(group_id: int) -> dict[str, Any]:
    """
    Regenerate the invitation code for a group. Anyone with this code can join the group. The old code will be invalidated.

    Args:
        group_id: The ID of the group.

    Returns:
        Success: {"message": str, "invitation_code": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
    }

    response = bridge.call_api(
        "splitwise", "regenerate_invitation_code", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_accept_group_invitation(invitation_code: str) -> dict[str, Any]:
    """
    Accept a group invitation shared with you by one of its members.

    Args:
        invitation_code: The group invitation shared with you by one of its members.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "invitation_code": invitation_code,
    }

    response = bridge.call_api(
        "splitwise", "accept_group_invitation", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_record_expense(
    description: str,
    paid_amount: float,
    payer_email: str,
    debtor_emails: list[str],
    debt_amounts: list[float] | None = None,
    group_id: int | None = None,
    receipt_file_path: str | None = None,
    file_system_access_token: str | None = None,
) -> dict[str, Any]:
    """
    Record a new expense to share with others.

    Args:
        description: A short note or description of the expense.
        paid_amount: The total amount of the expense paid.
        payer_email: Email of the user who paid for the expense. Must be a valid email address.
        debtor_emails: Emails of the users who owe a share of the expense.
        debt_amounts: The amounts owed by each debtor. If not passed, it is assumed that each debtor owes an equal share. If passed, the list must be of the same length as debtor_emails. (optional)
        group_id: The ID of the group this expense should belong to. Keep it none if it should not belong to any group. (optional)
        receipt_file_path: Absolute file path (starting with /) from the file_system app to attach as a receipt for this expense. (optional)
        file_system_access_token: Access token obtained from file_system app login. Only needed for attaching receipt file. (optional)

    Returns:
        Success: {"message": str, "expense_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "description": description,
        "paid_amount": paid_amount,
        "payer_email": payer_email,
        "debtor_emails": debtor_emails,
    }
    if debt_amounts is not None:
        params["debt_amounts"] = debt_amounts
    if group_id is not None:
        params["group_id"] = group_id
    if receipt_file_path is not None:
        params["receipt_file_path"] = receipt_file_path
    if file_system_access_token is not None:
        params["file_system_access_token"] = file_system_access_token

    response = bridge.call_api("splitwise", "record_expense", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_attach_expense_receipt_file(
    expense_id: int,
    receipt_file_path: str,
    file_system_access_token: str,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Attach a receipt file to an expense.

    Args:
        expense_id: The ID of the expense to attach receipt file to.
        receipt_file_path: Absolute file path (starting with /) from the file_system app to attach as a receipt for this expense.
        file_system_access_token: Access token obtained from file_system app login.
        overwrite: Whether to overwrite the existing receipt file if it already exists. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
        "receipt_file_path": receipt_file_path,
        "file_system_access_token": file_system_access_token,
    }
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api(
        "splitwise", "attach_expense_receipt_file", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_expense_receipt_file(expense_id: int) -> dict[str, Any]:
    """
    Delete the receipt file from an expense.

    Args:
        expense_id: The ID of the expense to detach receipt file from.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
    }

    response = bridge.call_api(
        "splitwise", "delete_expense_receipt_file", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_download_expense_receipt_file(
    expense_id: int,
    file_system_access_token: str,
    download_to_file_path: str | None = None,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Download a receipt file attachment for an expense.

    Args:
        expense_id: The ID of the expense to download receipt for.
        file_system_access_token: Access token obtained from file_system app login.
        download_to_file_path: The file path to download the receipt file to in file system app. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. If not passed, it will be saved in your ~/downloads directory. (optional)
        overwrite: Whether to overwrite the file if it already exists. (optional)

    Returns:
        Success: {"message": str, "file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
        "file_system_access_token": file_system_access_token,
    }
    if download_to_file_path is not None:
        params["download_to_file_path"] = download_to_file_path
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api(
        "splitwise", "download_expense_receipt_file", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_expense(expense_id: int) -> dict[str, Any]:
    """
    Show detailed expense information based on its ID.

    Args:
        expense_id: The ID of the expense.

    Returns:
        Success: {"expense_id": int, "group_id": int, "description": str, "deleted": bool, "receipt_file_name": str, "created_at": str (datetime), "shares": list[dict], "creator": dict, ...}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
    }

    response = bridge.call_api("splitwise", "show_expense", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_update_expense(
    expense_id: int,
    description: str | None = None,
    paid_amount: float | None = None,
    payer_email: str | None = None,
    debtor_emails: list[str] | None = None,
    debt_amounts: list[float] | None = None,
) -> dict[str, Any]:
    """
    Update expense information.

    Args:
        expense_id: The ID of the expense.
        description: The updated note or description of the expense. (optional)
        paid_amount: The updated total paid amount of the expense. (optional)
        payer_email: Email of updated user who paid for the expense. Must be a valid email address. (optional)
        debtor_emails: Emails of updated users who owe a share of the expense. (optional)
        debt_amounts: The updated amounts owed by each debtor. If debtor_emails is passed and debt_amounts is not passed, each debtor will owe an equal share. If debtor_emails is passed and debt_amounts is passed, the list must be of the same length as debtor_emails.If debt_amount is passed, debtor_emails must be passed. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
    }
    if description is not None:
        params["description"] = description
    if paid_amount is not None:
        params["paid_amount"] = paid_amount
    if payer_email is not None:
        params["payer_email"] = payer_email
    if debtor_emails is not None:
        params["debtor_emails"] = debtor_emails
    if debt_amounts is not None:
        params["debt_amounts"] = debt_amounts

    response = bridge.call_api("splitwise", "update_expense", method="patch", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_expense(expense_id: int) -> dict[str, Any]:
    """
    Mark the expense you are involved in as deleted. Anyone involved in the expense or a member of its group can undelete it later.

    Args:
        expense_id: The ID of the expense to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
    }

    response = bridge.call_api("splitwise", "delete_expense", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_group_expenses(
    group_id: int,
    query: str | None = "",
    participant_email: str | None = None,
    min_amount: float | None = 0.0,
    max_amount: float | None = 9.223372036854776e18,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    deleted: bool | None = False,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search your expenses from a given group based on various criteria.

    Args:
        group_id: The ID of the group to filter expenses.
        query: The search query string. (optional)
        participant_email: Email of the payer or debtors to filter expenses. Must be a valid email address. (optional)
        min_amount: Filter expenses by minimum amount. Must be >= 0.0. (optional)
        max_amount: Filter expenses by maximum amount. Must be >= 0.0. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        deleted: Whether to limit the results to expenses marked as deleted or not. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the expenses by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and amount. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -created_at. (optional)

    Returns:
        Success: [{"expense_id": int, "group_id": int, "description": str, "deleted": bool, "receipt_file_name": str, "created_at": str (datetime), "shares": list[dict], "creator": dict, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
    }
    if query is not None:
        params["query"] = query
    if participant_email is not None:
        params["participant_email"] = participant_email
    if min_amount is not None:
        params["min_amount"] = min_amount
    if max_amount is not None:
        params["max_amount"] = max_amount
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if deleted is not None:
        params["deleted"] = deleted
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api(
        "splitwise", "show_group_expenses", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_no_group_expenses(
    query: str | None = "",
    participant_email: str | None = None,
    min_amount: float | None = 0.0,
    max_amount: float | None = 9.223372036854776e18,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    deleted: bool | None = False,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Show or search your expenses that are not part of any group based on various criteria.

    Args:
        query: The search query string. (optional)
        participant_email: Email of the payer or debtors to filter expenses. Must be a valid email address. (optional)
        min_amount: Filter expenses by minimum amount. Must be >= 0.0. (optional)
        max_amount: Filter expenses by maximum amount. Must be >= 0.0. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        deleted: Whether to limit the results to expenses marked as deleted or not. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the expenses by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -created_at. (optional)

    Returns:
        Success: [{"expense_id": int, "group_id": int, "description": str, "deleted": bool, "receipt_file_name": str, "created_at": str (datetime), "shares": list[dict], "creator": dict, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if query is not None:
        params["query"] = query
    if participant_email is not None:
        params["participant_email"] = participant_email
    if min_amount is not None:
        params["min_amount"] = min_amount
    if max_amount is not None:
        params["max_amount"] = max_amount
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if deleted is not None:
        params["deleted"] = deleted
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api(
        "splitwise", "show_no_group_expenses", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_undelete_expense(expense_id: int) -> dict[str, Any]:
    """
    Restore a previously deleted expense you are involved in.

    Args:
        expense_id: The ID of the expense to undelete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
    }

    response = bridge.call_api(
        "splitwise", "undelete_expense", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_post_expense_comment(expense_id: int, comment: str) -> dict[str, Any]:
    """
    Post a comment on an expense.

    Args:
        expense_id: The ID of the expense.
        comment: The comment for the expense. Length must be between 1 and 1000.

    Returns:
        Success: {"message": str, "expense_comment_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
        "comment": comment,
    }

    response = bridge.call_api(
        "splitwise", "post_expense_comment", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_expense_comments(
    expense_id: int, page_index: int | None = 0, page_limit: int | None = 5
) -> list[dict[str, Any]]:
    """
    Get a list of expense comments.

    Args:
        expense_id: The ID of the expense.
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"expense_comment_id": int, "expense_id": int, "comment": str, "created_at": str (datetime), "user": dict}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "expense_id": expense_id,
    }
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api(
        "splitwise", "show_expense_comments", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_update_expense_comment(comment_id: int, comment: str) -> dict[str, Any]:
    """
    Update a comment you posted on an expense.

    Args:
        comment_id: The ID of the expense comment to update.
        comment: The updated comment for the expense. Minimum length: 1.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "comment_id": comment_id,
        "comment": comment,
    }

    response = bridge.call_api(
        "splitwise", "update_expense_comment", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_expense_comment(comment_id: int) -> dict[str, Any]:
    """
    Delete a comment you posted on an expense.

    Args:
        comment_id: The ID of the expense comment to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "comment_id": comment_id,
    }

    response = bridge.call_api(
        "splitwise", "delete_expense_comment", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_expense_comment(comment_id: int) -> dict[str, Any]:
    """
    Get information about a comment posted on an expense.

    Args:
        comment_id: The ID of the expense comment.

    Returns:
        Success: {"expense_comment_id": int, "expense_id": int, "comment": str, "created_at": str (datetime), "user": dict}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "comment_id": comment_id,
    }

    response = bridge.call_api(
        "splitwise", "show_expense_comment", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_record_payment(
    payer_email: str,
    receiver_email: str,
    amount: float,
    group_id: int | None = None,
    description: str | None = None,
    receipt_file_path: str | None = None,
    file_system_access_token: str | None = None,
) -> dict[str, Any]:
    """
    Record a new payment for an expense. This only records payment on splitwise and does not move real money.

    Args:
        payer_email: Email of the user who made the payment. Must be a valid email address.
        receiver_email: Email of the user who received the payment. Must be a valid email address.
        amount: The amount of the payment.
        group_id: The ID of the group to record the payment in. (optional)
        description: A short note or description of the payment. (optional)
        receipt_file_path: Receipt file path to attach as an evidence of this payment made (e.g., snapshot of bank transfer, venmo, etc.) (optional)
        file_system_access_token: Access token obtained from file_system app login. Only needed for attaching receipt file. (optional)

    Returns:
        Success: {"message": str, "payment_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payer_email": payer_email,
        "receiver_email": receiver_email,
        "amount": amount,
    }
    if group_id is not None:
        params["group_id"] = group_id
    if description is not None:
        params["description"] = description
    if receipt_file_path is not None:
        params["receipt_file_path"] = receipt_file_path
    if file_system_access_token is not None:
        params["file_system_access_token"] = file_system_access_token

    response = bridge.call_api("splitwise", "record_payment", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_attach_payment_receipt_file(
    payment_id: int,
    receipt_file_path: str,
    file_system_access_token: str,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Attach a receipt file to a payment.

    Args:
        payment_id: The ID of the payment to attach receipt to.
        receipt_file_path: The file path of the receipt file to attach to this payment.
        file_system_access_token: Access token obtained from file_system app login.
        overwrite: Whether to overwrite the existing receipt file if it already exists. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
        "receipt_file_path": receipt_file_path,
        "file_system_access_token": file_system_access_token,
    }
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api(
        "splitwise", "attach_payment_receipt_file", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_payment_receipt_file(payment_id: int) -> dict[str, Any]:
    """
    Delete the receipt file from a payment.

    Args:
        payment_id: The ID of the payment to delete receipt for.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
    }

    response = bridge.call_api(
        "splitwise", "delete_payment_receipt_file", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_download_payment_receipt_file(
    payment_id: int,
    file_system_access_token: str,
    download_to_file_path: str | None = None,
    overwrite: bool | None = False,
) -> dict[str, Any]:
    """
    Download receipt file attachment for a payment.

    Args:
        payment_id: The ID of the payment to download receipt for.
        file_system_access_token: Access token obtained from file_system app login.
        download_to_file_path: The file path to download the receipt file to in file system app. Path can be absolute, starting with '/', or relative to the user's home directory, starting with '~/'. If not passed, it will be saved in your ~/downloads directory. (optional)
        overwrite: Whether to overwrite the file if it already exists. (optional)

    Returns:
        Success: {"message": str, "file_path": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
        "file_system_access_token": file_system_access_token,
    }
    if download_to_file_path is not None:
        params["download_to_file_path"] = download_to_file_path
    if overwrite is not None:
        params["overwrite"] = overwrite

    response = bridge.call_api(
        "splitwise", "download_payment_receipt_file", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_payment(payment_id: int) -> dict[str, Any]:
    """
    Show payment details based on its ID.

    Args:
        payment_id: The ID of the payment.

    Returns:
        Success: {"payment_id": int, "group_id": int, "description": str, "deleted": bool, "receipt_file_name": str, "created_at": str (datetime), "creator": dict, "payer": dict, ...}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
    }

    response = bridge.call_api("splitwise", "show_payment", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_update_payment(
    payment_id: int, amount: float | None = None, description: str | None = None
) -> dict[str, Any]:
    """
    Update payment information.

    Args:
        payment_id: The ID of the payment.
        amount: The updated amount of the payment. (optional)
        description: The updated note or description of the payment. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
    }
    if amount is not None:
        params["amount"] = amount
    if description is not None:
        params["description"] = description

    response = bridge.call_api("splitwise", "update_payment", method="patch", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_payment(payment_id: int) -> dict[str, Any]:
    """
    Mark the payment you are involved in as deleted. Anyone involved in the payment or a member of its group can undelete it later.

    Args:
        payment_id: The ID of the payment to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
    }

    response = bridge.call_api("splitwise", "delete_payment", method="delete", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_group_payments(
    group_id: int,
    query: str | None = "",
    participant_email: str | None = None,
    min_amount: float | None = 0.0,
    max_amount: float | None = 9.223372036854776e18,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    deleted: bool | None = False,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Search or show the payments that are part of the given group.

    Args:
        group_id: The ID of the group to filter payments.
        query: The search query string. (optional)
        participant_email: Email of the payer or receiver to filter payments. Must be a valid email address. (optional)
        min_amount: Filter expenses by minimum amount. Must be >= 0.0. (optional)
        max_amount: Filter expenses by maximum amount. Must be >= 0.0. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        deleted: Filter expenses by deleted status. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the payments by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and amount. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -created_at. (optional)

    Returns:
        Success: [{"payment_id": int, "group_id": int, "description": str, "deleted": bool, "receipt_file_name": str, "created_at": str (datetime), "creator": dict, "payer": dict, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "group_id": group_id,
    }
    if query is not None:
        params["query"] = query
    if participant_email is not None:
        params["participant_email"] = participant_email
    if min_amount is not None:
        params["min_amount"] = min_amount
    if max_amount is not None:
        params["max_amount"] = max_amount
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if deleted is not None:
        params["deleted"] = deleted
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api(
        "splitwise", "show_group_payments", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_no_group_payments(
    query: str | None = "",
    participant_email: str | None = None,
    min_amount: float | None = 0.0,
    max_amount: float | None = 9.223372036854776e18,
    min_created_at: str | None = "1500-01-01",
    max_created_at: str | None = "3000-01-01",
    deleted: bool | None = False,
    page_index: int | None = 0,
    page_limit: int | None = 5,
    sort_by: str | None = None,
) -> list[dict[str, Any]]:
    """
    Search or show payments you are involved in that are not part of any group.

    Args:
        query: The search query string. (optional)
        participant_email: Email of the payer or receiver to filter payments. Must be a valid email address. (optional)
        min_amount: Filter expenses by minimum amount. Must be >= 0.0. (optional)
        max_amount: Filter expenses by maximum amount. Must be >= 0.0. (optional)
        min_created_at: Filter emails by minimum created_at date in YYYY-MM-DD format. (optional)
        max_created_at: Filter emails by maximum created_at date in YYYY-MM-DD format. (optional)
        deleted: Filter payments by deleted status. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)
        sort_by: The attribute to sort the payments by prefixed with +/- to reflect ascending/descending. Valid attributes: created_at and amount. If both query and sort_by are given and non-empty, results will be first ranked by query relevance, then paginated, and will then be sorted by the given attribute within each page. If both query and sort_by are not given, null, or empty, sort_by will default to -created_at. (optional)

    Returns:
        Success: [{"payment_id": int, "group_id": int, "description": str, "deleted": bool, "receipt_file_name": str, "created_at": str (datetime), "creator": dict, "payer": dict, ...}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if query is not None:
        params["query"] = query
    if participant_email is not None:
        params["participant_email"] = participant_email
    if min_amount is not None:
        params["min_amount"] = min_amount
    if max_amount is not None:
        params["max_amount"] = max_amount
    if min_created_at is not None:
        params["min_created_at"] = min_created_at
    if max_created_at is not None:
        params["max_created_at"] = max_created_at
    if deleted is not None:
        params["deleted"] = deleted
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit
    if sort_by is not None:
        params["sort_by"] = sort_by

    response = bridge.call_api(
        "splitwise", "show_no_group_payments", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_undelete_payment(payment_id: int) -> dict[str, Any]:
    """
    Restore a previously deleted payment you are involved in.

    Args:
        payment_id: The ID of the payment to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
    }

    response = bridge.call_api(
        "splitwise", "undelete_payment", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_person_balance(email: str) -> dict[str, Any]:
    """
    Show the amounts you and a given person owe to each other, broken down by group. The non-grouped expenses/payments will be shown as a group with ID None.

    Args:
        email: The email of the person to show your balance with. Must be a valid email address.

    Returns:
        Success: {"direction": str, "total": float, "breakdown": list[dict]}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "email": email,
    }

    response = bridge.call_api(
        "splitwise", "show_person_balance", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_people_balance() -> dict[str, Any]:
    """
    Show the aggregate amounts you owe to each person and they owe to you.

    Returns:
        Success: {"you_owe_others": float, "others_owe_you": float, "breakdown": list[dict]}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }

    response = bridge.call_api(
        "splitwise", "show_people_balance", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_group_balance(
    group_id: int | None = None, email: str | None = None
) -> list[dict[str, Any]]:
    """
    For the given group, show the detailed breakdown of amounts different members owe to each other. If group_id is not passed, show the amounts you owe to others and vice-versa for non-grouped expenses/payments.

    Args:
        group_id: The ID of the group to show balance of. If not passed, it will show balance from non-grouped expenses/payments. (optional)
        email: If passed, only balance of this member of the group will be shown. Otherwise, balance of all members will be shown. If group_id is not passed, email can only be your own email or None. Must be a valid email address. (optional)

    Returns:
        Success: [{"source": dict, "source_owes_to_targets": dict, "targets_owe_to_source": dict}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if group_id is not None:
        params["group_id"] = group_id
    if email is not None:
        params["email"] = email

    response = bridge.call_api(
        "splitwise", "show_group_balance", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_groups_balance() -> dict[str, Any]:
    """
    Show the aggregate amounts you owe to others or others owe you for each group you are member of. The non-grouped expenses/payments will be shown as a group with group_id of None.

    Returns:
        Success: {"you_owe_others": float, "others_owe_you": float, "breakdown": list[dict]}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }

    response = bridge.call_api(
        "splitwise", "show_groups_balance", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_settle_up(
    email: str,
    group_id: int | None = None,
    description: str | None = "Settle up balance.",
) -> dict[str, Any]:
    """
    Settle up outstanding balance with a user in a group. This only records payment on splitwise and does not move real money.

    Args:
        email: The email of the user to settle balance with. Must be a valid email address.
        group_id: The ID of the group to settle balance. (optional)
        description: The description of the payment. (optional)

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "email": email,
    }
    if group_id is not None:
        params["group_id"] = group_id
    if description is not None:
        params["description"] = description

    response = bridge.call_api("splitwise", "settle_up", method="post", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_post_payment_comment(payment_id: int, comment: str) -> dict[str, Any]:
    """
    Create a new payment comment.

    Args:
        payment_id: The ID of the payment.
        comment: The comment for the payment.

    Returns:
        Success: {"message": str, "payment_comment_id": int}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
        "comment": comment,
    }

    response = bridge.call_api(
        "splitwise", "post_payment_comment", method="post", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_payment_comments(payment_id: int) -> list[dict[str, Any]]:
    """
    Get a list of payment comments.

    Args:
        payment_id: The ID of the payment.

    Returns:
        Success: [{"payment_comment_id": int, "payment_id": int, "comment": str, "created_at": str (datetime), "user": dict}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "payment_id": payment_id,
    }

    response = bridge.call_api(
        "splitwise", "show_payment_comments", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_update_payment_comment(comment_id: int, comment: str) -> dict[str, Any]:
    """
    Update a payment comment.

    Args:
        comment_id: The ID of the payment comment to update.
        comment: The updated comment for the payment. Minimum length: 1.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "comment_id": comment_id,
        "comment": comment,
    }

    response = bridge.call_api(
        "splitwise", "update_payment_comment", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_payment_comment(comment_id: int) -> dict[str, Any]:
    """
    Delete a comment you posted on a payment.

    Args:
        comment_id: The ID of the payment comment to delete.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "comment_id": comment_id,
    }

    response = bridge.call_api(
        "splitwise", "delete_payment_comment", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_payment_comment(comment_id: int) -> dict[str, Any]:
    """
    Get information about a comment posted on a payment.

    Args:
        comment_id: The ID of the payment comment.

    Returns:
        Success: {"payment_comment_id": int, "payment_id": int, "comment": str, "created_at": str (datetime), "user": dict}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "comment_id": comment_id,
    }

    response = bridge.call_api(
        "splitwise", "show_payment_comment", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_notifications(
    read: bool | None = None,
    page_index: int | None = 0,
    page_limit: int | None = 5,
) -> list[dict[str, Any]]:
    """
    Get a list of your notifications.

    Args:
        read: Filter notifications by read status. Will skip filtering if not passed. (optional)
        page_index: The index of the page to return. Must be >= 0. (optional)
        page_limit: The maximum number of results to return per page. Must be between 1 and 20. (optional)

    Returns:
        Success: [{"notification_id": int, "type": str, "title": str, "message": str, "read": bool, "created_at": str (datetime), "data": dict}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if read is not None:
        params["read"] = read
    if page_index is not None:
        params["page_index"] = page_index
    if page_limit is not None:
        params["page_limit"] = page_limit

    response = bridge.call_api(
        "splitwise", "show_notifications", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_notifications() -> dict[str, Any]:
    """
    Delete all of your notifications.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }

    response = bridge.call_api(
        "splitwise", "delete_notifications", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_mark_notifications(read: bool) -> dict[str, Any]:
    """
    Mark all notifications as read or unread.

    Args:
        read: Read status of the notification.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "read": read,
    }

    response = bridge.call_api(
        "splitwise", "mark_notifications", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_show_notifications_count(read: bool | None = None) -> dict[str, Any]:
    """
    Get the count of your notifications.

    Args:
        read: Count notifications by read status. Will count all if not passed. (optional)

    Returns:
        Success: {"notifications_count": float}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
    }
    if read is not None:
        params["read"] = read

    response = bridge.call_api(
        "splitwise", "show_notifications_count", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_delete_notification(notification_id: int) -> dict[str, Any]:
    """
    Delete a notification.

    Args:
        notification_id: The ID of the notification.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "notification_id": notification_id,
    }

    response = bridge.call_api(
        "splitwise", "delete_notification", method="delete", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("splitwise")
@requires_network
@requires_auth("splitwise")
def splitwise_mark_notification(notification_id: int, read: bool) -> dict[str, Any]:
    """
    Mark a notification as read or unread.

    Args:
        notification_id: ID of the notification to mark.
        read: Mark the notification as read or unread.

    Returns:
        Success: {"message": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {
        "access_token": appworld_state.get_access_token("splitwise"),
        "notification_id": notification_id,
        "read": read,
    }

    response = bridge.call_api(
        "splitwise", "mark_notification", method="patch", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}
