"""
Supervisor API tools for MMToolSandbox.

This module wraps AppWorld's Supervisor APIs as MMToolSandbox-compatible tools
with state dependency checks (network, authentication).

Auto-generated by generate_static_wrappers.py
"""

from typing import Any

from mmtoolsandbox.appworld.bridge import get_appworld_bridge
from mmtoolsandbox.appworld.state import (
    get_appworld_state,
    requires_network,
)
from mmtoolsandbox.tools.appworld import register_appworld_tool

# NOTE: The following two functions are commented out because they are vestigial
# leftovers from native AppWorld and are not needed in the MMToolSandbox paradigm:
#
# 1. supervisor_show_active_task: In MMToolSandbox, the task instruction is provided
#    directly to the agent in the initial chat message from the user simulator. The
#    agent does not need to query an API to find out what its task is.
#
# 2. supervisor_complete_task: In MMToolSandbox, evaluation is handled programmatically
#    (via Milestones and an LLM Judge) after the user simulator calls `end_conversation`.
#    The agent simply tells the user when it is done in a standard chat message, rather
#    than explicitly submitting an answer to the AppWorld environment.
#
# @register_appworld_tool("supervisor")
# @requires_network
# def supervisor_show_active_task() -> dict[str, Any]:
#     """
#     Show the currently active task assigned to you by the supervisor.
#
#     Returns:
#         dict[str, Any]
#
#     Raises:
#         ConnectionError: If network is unavailable
#     """
#     bridge = get_appworld_bridge()
#     appworld_state = get_appworld_state()
#
#     params: dict[str, Any] = {}
#
#     response = bridge.call_api("supervisor", "show_active_task", method="get", **params)
#
#     if isinstance(response, dict) and "error" in response:
#         raise ValueError(f"API error: {response['error']}")
#
#     return dict(response) if isinstance(response, dict) else {}
#
#
# @register_appworld_tool("supervisor")
# @requires_network
# def supervisor_complete_task(
#     answer: Optional[Any] = None, status: Optional[str] = "success"
# ) -> dict[str, Any]:
#     """
#     Mark the currently active task as complete with the given answer.
#
#     Args:
#         answer: The answer to the task instruction. Pass it if and only if the task requests an answer, e.g., 'How many songs are in the Spotify queue?'. The answer must be concise, such as a number, a yes/no, or a specific entity, name, etc, e.g., '10' in this case. If the task is not a question, e.g., 'Start my Spotify music player.', the answer must be left to the default value, i.e., None. (optional)
#         status: Mark the task complete. (optional)
#
#     Returns:
#         dict[str, Any]
#
#     Raises:
#         ConnectionError: If network is unavailable
#     """
#     bridge = get_appworld_bridge()
#     appworld_state = get_appworld_state()
#
#     params: dict[str, Any] = {}
#     if answer is not None:
#         params["answer"] = answer
#     if status is not None:
#         params["status"] = status
#
#     response = bridge.call_api("supervisor", "complete_task", method="post", **params)
#
#     if isinstance(response, dict) and "error" in response:
#         raise ValueError(f"API error: {response['error']}")
#
#     # End the conversation immediately after task completion
#     # This matches AppWorld's StopAtTools behavior
#     end_conversation()
#
#     return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("supervisor")
@requires_network
def supervisor_show_profile() -> dict[str, Any]:
    """
    Show your supervisor's profile information.

    Returns:
        Success: {"first_name": str, "last_name": str, "email": str, "phone_number": str, "birthday": str, "sex": str}
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}

    response = bridge.call_api("supervisor", "show_profile", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    return dict(response) if isinstance(response, dict) else {}


@register_appworld_tool("supervisor")
@requires_network
def supervisor_show_addresses() -> list[dict[str, Any]]:
    """
    Show your supervisor's addresses.

    Returns:
        Success: [{"name": str, "street_address": str, "city": str, "state": str, "country": str, "zip_code": float}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}

    response = bridge.call_api("supervisor", "show_addresses", method="get", **params)

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("supervisor")
@requires_network
def supervisor_show_payment_cards() -> list[dict[str, Any]]:
    """
    Show your supervisor's payment_cards.

    Returns:
        Success: [{"owner_name": str, "card_name": str, "card_number": float, "expiry_year": int, "expiry_month": float, "cvv_number": float}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}

    response = bridge.call_api(
        "supervisor", "show_payment_cards", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []


@register_appworld_tool("supervisor")
@requires_network
def supervisor_show_account_passwords() -> list[dict[str, Any]]:
    """
    Show your supervisor's app account passwords.

    Returns:
        Success: [{"account_name": str, "password": str}]
        Failure: {"message": str}
    """
    bridge = get_appworld_bridge()
    appworld_state = get_appworld_state()

    params: dict[str, Any] = {}

    response = bridge.call_api(
        "supervisor", "show_account_passwords", method="get", **params
    )

    if isinstance(response, dict) and "error" in response:
        raise ValueError(f"API error: {response['error']}")

    # Extract list from response
    if isinstance(response, list):
        return list(response)
    if isinstance(response, dict):
        # Try common list keys
        for key in response:
            if isinstance(response[key], list):
                return list(response[key])
    return []
